using System;
using System.Collections.Generic;

#nullable disable

namespace USAIDICANBLAZOR.Models
{
    public partial class OnaAgyw2020
    {
        public double Id { get; set; }
        public string Start { get; set; }
        public string Endd { get; set; }
        public string Deviceid { get; set; }
        public string District { get; set; }
        public string Fo { get; set; }
        public string Subcounty { get; set; }
        public string Village { get; set; }
        public string CalcYr { get; set; }
        public string CurrYr { get; set; }
        public string CurrMth { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string SectionAFname { get; set; }
        public string SectionASurname { get; set; }
        public double? SectionAAge { get; set; }
        public string SectionALiveWith { get; set; }
        public bool SectionALiveWith1 { get; set; }
        public bool SectionALiveWith2 { get; set; }
        public bool SectionALiveWith3 { get; set; }
        public bool SectionALiveWith4 { get; set; }
        public bool SectionALiveWith5 { get; set; }
        public string SectionAOtherRelative { get; set; }
        public string SectionAMs { get; set; }
        public string SectionAPreg { get; set; }
        public string SectionAChildren { get; set; }
        public double? SectionAAgeBirth { get; set; }
        public string SectionADisable { get; set; }
        public string SectionADisable2 { get; set; }
        public string SectionADisable21 { get; set; }
        public string SectionADisable22 { get; set; }
        public string SectionADisable23 { get; set; }
        public string SectionADisable24 { get; set; }
        public string SectionAOtherDisable { get; set; }
        public string SectionAEduc { get; set; }
        public string SectionANoschool { get; set; }
        public bool SectionANoschool1 { get; set; }
        public bool SectionANoschool2 { get; set; }
        public bool SectionANoschool3 { get; set; }
        public bool SectionANoschool4 { get; set; }
        public bool SectionANoschool5 { get; set; }
        public bool SectionANoschool6 { get; set; }
        public bool SectionANoschool7 { get; set; }
        public bool SectionANoschool10 { get; set; }
        public bool SectionANoschool8 { get; set; }
        public bool SectionANoschool9 { get; set; }
        public bool SectionANoschool11 { get; set; }
        public bool SectionANoschool12 { get; set; }
        public bool SectionANoschool13 { get; set; }
        public string SectionAOther { get; set; }
        public string SectionARead { get; set; }
        public bool SectionARead1 { get; set; }
        public bool SectionARead2 { get; set; }
        public string SectionAAct { get; set; }
        public bool SectionARead3 { get; set; }
        public bool SectionARead4 { get; set; }
        public bool SectionAAct1 { get; set; }
        public bool SectionAAct2 { get; set; }
        public bool SectionAAct3 { get; set; }
        public bool SectionAAct4 { get; set; }
        public bool SectionAAct5 { get; set; }
        public bool SectionAAct6 { get; set; }
        public bool SectionAAct7 { get; set; }
        public bool SectionAAct10 { get; set; }
        public bool SectionAAct8 { get; set; }
        public bool SectionAAct9 { get; set; }
        public bool SectionAAct11 { get; set; }
        public string SectionBLiveAct { get; set; }
        public string SectionBLiveTr { get; set; }
        public string SectionBSrcLiveTr { get; set; }
        public string SectionBSrcLiveAct { get; set; }
        public string SectionBBiz { get; set; }
        public bool SectionBBiz1 { get; set; }
        public bool SectionBBiz2 { get; set; }
        public bool SectionBBiz3 { get; set; }
        public bool SectionBBiz4 { get; set; }
        public bool SectionBBiz5 { get; set; }
        public bool SectionBBiz6 { get; set; }
        public string SectionBMoney { get; set; }
        public bool SectionBMoney1 { get; set; }
        public bool SectionBMoney2 { get; set; }
        public bool SectionBMoney3 { get; set; }
        public bool SectionBMoney4 { get; set; }
        public bool SectionBMoney5 { get; set; }
        public bool SectionBMoney6 { get; set; }
        public bool SectionBMoney7 { get; set; }
        public bool SectionBMoney10 { get; set; }
        public bool SectionBMoney8 { get; set; }
        public bool SectionBMoney9 { get; set; }
        public bool SectionBMoney11 { get; set; }
        public string SectionBIncome { get; set; }
        public bool SectionBMoney12 { get; set; }
        public string SectionBOtherMoney { get; set; }
        public string SectionBSpent { get; set; }
        public bool SectionBSpent1 { get; set; }
        public bool SectionBSpent2 { get; set; }
        public bool SectionBSpent3 { get; set; }
        public bool SectionBSpent4 { get; set; }
        public bool SectionBSpent5 { get; set; }
        public string SectionBOtherSpent { get; set; }
        public bool SectionBSpent6 { get; set; }
        public bool SectionBSpent7 { get; set; }
        public string SectionBSavingGrp { get; set; }
        public string SectionBMake { get; set; }
        public bool SectionBMake1 { get; set; }
        public bool SectionBMake2 { get; set; }
        public bool SectionBMake3 { get; set; }
        public bool SectionBMake4 { get; set; }
        public string Sec2sectionAPrepost1 { get; set; }
        public bool SectionBMake5 { get; set; }
        public string SectionBOtherMake { get; set; }
        public string Sec2sectionAPrepost2 { get; set; }
        public string Sec2sectionAPrepost3 { get; set; }
        public string Sec2sectionAPrepost4 { get; set; }
        public string Sec2sectionAPrepost5 { get; set; }
        public string Sec2sectionAPrepost6 { get; set; }
        public string Sec2sectionAPrepost7 { get; set; }
        public string Sec2sectionAPrepost8 { get; set; }
        public string Sec2sectionBPrepost9 { get; set; }
        public string Sec2sectionBPrepost10 { get; set; }
        public string Sec2sectionBPrepost11 { get; set; }
        public string Sec2sectionBPrepost12 { get; set; }
        public string Sec2sectionBPrepost13 { get; set; }
        public string Sec2sectionBPrepost14 { get; set; }
        public string Sec2sectionBPrepost15 { get; set; }
        public string Sec2sectionBPrepost16 { get; set; }
        public string Sec2sectionCPrepost17 { get; set; }
        public string Sec2sectionCOtherPrepost19 { get; set; }
        public string Sec2sectionCPrepost18 { get; set; }
        public string Sec2sectionCPrepost19 { get; set; }
        public string Sec2sectionCOtherPrepost21 { get; set; }
        public string Sec2sectionCPrepost20 { get; set; }
        public string Sec2sectionCPrepost21 { get; set; }
        public string Sec2sectionCPrepost22 { get; set; }
        public string Sec2sectionDPrepost23 { get; set; }
        public string Sec2sectionDPrepost24 { get; set; }
        public string Sec2sectionDPrepost25 { get; set; }
        public string Sec2sectionDPrepost26 { get; set; }
        public string Sec2sectionDPrepost27 { get; set; }
        public string Sec2sectionDPrepost28 { get; set; }
        public string Sec2sectionEPrepost29 { get; set; }
        public string Sec2sectionEPrepost30 { get; set; }
        public string Sec2sectionEPrepost31 { get; set; }
        public string Sec2sectionEPrepost32 { get; set; }
        public string Sec2sectionEPrepost33 { get; set; }
        public string Sec2sectionEPrepost34 { get; set; }
        public string Sec2sectionFPrepost35 { get; set; }
        public string Sec2sectionFPrepost36 { get; set; }
        public string Sec2sectionFPrepost37 { get; set; }
        public string Sec2sectionFPrepost38 { get; set; }
        public string Sec2sectionFPrepost39 { get; set; }
        public string Sec2sectionFPrepost40 { get; set; }
        public string Sec2sectionGPrepost41 { get; set; }
        public string Sec2sectionGPrepost42 { get; set; }
        public string Sec2sectionGPrepost43 { get; set; }
        public string Sec2sectionGPrepost44 { get; set; }
        public string Sec2sectionGPrepost45 { get; set; }
        public string MetaInstanceId { get; set; }
        public string Sec2sectionGPrepost46 { get; set; }
        public string Sec2sectionGPrepost47 { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public string Uuid { get; set; }
        public DateTime? SubmissionTime { get; set; }
        public double? Index { get; set; }
        public string ParentTableName { get; set; }
        public double? ParentIndex { get; set; }
        public string Tags { get; set; }
        public string Notes { get; set; }
        public string Version { get; set; }
        public double? Duration { get; set; }
        public string SubmittedBy { get; set; }
        public double? XformId { get; set; }
        public DateTime? LastUpdatedAt { get; set; }
    }
}
