using System;
using System.Collections.Generic;

#nullable disable

namespace USAIDICANBLAZOR.Models
{
    public partial class OnabaselinePhaseIi
    {
        public string Ra { get; set; }
        public string AZ2 { get; set; }
        public string AZ3 { get; set; }
        public string ADeviceid { get; set; }
        public string APhonenumber { get; set; }
        public string ARegionRegion { get; set; }
        public string ARegionDistrict { get; set; }
        public string ARegionSubcounty { get; set; }
        public string ARegionParish { get; set; }
        public string ARegion { get; set; }
        public string AHid { get; set; }
        public string AZ6 { get; set; }
        public string AZ7 { get; set; }
        public string AZ7a { get; set; }
        public string AZ8 { get; set; }
        public string QnBSexres { get; set; }
        public double? QnBAge { get; set; }
        public string QnCCNote { get; set; }
        public string QnCC1 { get; set; }
        public string QnCC2 { get; set; }
        public double? QnCC3 { get; set; }
        public string QnCC4 { get; set; }
        public string QnCC4Other { get; set; }
        public string QnCC5 { get; set; }
        public string QnCC6 { get; set; }
        public string QnCC6Other { get; set; }
        public double? QnCC10 { get; set; }
        public double? QnCC11 { get; set; }
        public double? QnCC12 { get; set; }
        public double? QnCC13 { get; set; }
        public double? QnCC14 { get; set; }
        public string QnCLesspri { get; set; }
        public double? QnCC15 { get; set; }
        public double? QnCC16 { get; set; }
        public double? QnCC17 { get; set; }
        public string QnFFIntro { get; set; }
        public string QnFF1 { get; set; }
        public double? QnFF1a { get; set; }
        public double? QnFF2 { get; set; }
        public string QnFF3 { get; set; }
        public string QnFF4 { get; set; }
        public string QnFF4Other { get; set; }
        public double? QnFF5 { get; set; }
        public string QnFF6 { get; set; }
        public string QnFF7 { get; set; }
        public string QnFF7Other { get; set; }
        public string QnFF8 { get; set; }
        public string QnFF8Other { get; set; }
        public string QnFF9 { get; set; }
        public string QnFF11 { get; set; }
        public string QnFF12 { get; set; }
        public string QnFF12Other { get; set; }
        public string QnFF131 { get; set; }
        public string QnFF132 { get; set; }
        public string QnFF133 { get; set; }
        public string QnFF14 { get; set; }
        public string QnFF15 { get; set; }
        public bool QnFF151 { get; set; }
        public bool QnFF152 { get; set; }
        public bool QnFF153 { get; set; }
        public bool QnFF154 { get; set; }
        public bool QnFF155 { get; set; }
        public bool QnFF156 { get; set; }
        public bool QnFF157 { get; set; }
        public string QnFF16 { get; set; }
        public string QnFF17 { get; set; }
        public string QnFF17a { get; set; }
        public string QnFF18 { get; set; }
        public string QnFF18a { get; set; }
        public string QnFF19 { get; set; }
        public string QnFF19a { get; set; }
        public string QnFF20 { get; set; }
        public string QnFF20a { get; set; }
        public string QnFF21 { get; set; }
        public string QnFF21a { get; set; }
        public string QnSectionRMis { get; set; }
        public bool QnSectionRMis1 { get; set; }
        public bool QnSectionRMis2 { get; set; }
        public bool QnSectionRMis3 { get; set; }
        public bool QnSectionRMis4 { get; set; }
        public bool QnSectionRMis5 { get; set; }
        public bool QnSectionRMis6 { get; set; }
        public bool QnSectionRMis7 { get; set; }
        public bool QnSectionRMis8 { get; set; }
        public bool QnSectionRMis9 { get; set; }
        public bool QnSectionRMis10 { get; set; }
        public bool QnSectionRMis11 { get; set; }
        public bool QnSectionRMis12 { get; set; }
        public bool QnSectionRMis13 { get; set; }
        public bool QnSectionRMis14 { get; set; }
        public bool QnSectionRMis15 { get; set; }
        public bool QnSectionRMis16 { get; set; }
        public bool QnSectionRMis17 { get; set; }
        public bool QnSectionRMis18 { get; set; }
        public bool QnSectionRMis19 { get; set; }
        public double? QnRankingRSrcIncome1 { get; set; }
        public string QnRankingRSrcIncome2 { get; set; }
        public string QnRankingRSrcIncome3 { get; set; }
        public string QnRankingRSrcIncome4 { get; set; }
        public double? QnRankingRSrcIncome5 { get; set; }
        public double? QnRankingRSrcIncome6 { get; set; }
        public double? QnRankingRSrcIncome7 { get; set; }
        public double? QnRankingRSrcIncome8 { get; set; }
        public double? QnRankingRSrcIncome9 { get; set; }
        public string QnRankingRSrcIncome10 { get; set; }
        public string QnRankingRSrcIncome11 { get; set; }
        public string QnRankingRSrcIncome12 { get; set; }
        public string QnRankingRSrcIncome13 { get; set; }
        public double? QnRankingRSrcIncome14 { get; set; }
        public string QnRankingRSrcIncome15 { get; set; }
        public string QnRankingRSrcIncome16 { get; set; }
        public string QnRankingRSrcIncome17 { get; set; }
        public string QnRankingRSrcIncome18 { get; set; }
        public string QnRankingRSrcIncome19 { get; set; }
        public double? QnSecionII1 { get; set; }
        public double? QnSecionII2 { get; set; }
        public double? QnSecionII2a { get; set; }
        public string QnSecionII3 { get; set; }
        public double? QnSecionII4 { get; set; }
        public string QnSecionII5 { get; set; }
        public string QnSecionII6 { get; set; }
        public string QnSecionII7 { get; set; }
        public bool QnSecionII71 { get; set; }
        public bool QnSecionII72 { get; set; }
        public bool QnSecionII73 { get; set; }
        public bool QnSecionII74 { get; set; }
        public bool QnSecionII75 { get; set; }
        public bool QnSecionII76 { get; set; }
        public string QnChrFoodgrps { get; set; }
        public bool QnChrFoodgrps1 { get; set; }
        public bool QnChrFoodgrps2 { get; set; }
        public bool QnChrFoodgrps3 { get; set; }
        public bool QnChrFoodgrps4 { get; set; }
        public bool QnChrFoodgrps5 { get; set; }
        public bool QnChrFoodgrps6 { get; set; }
        public bool QnChrFoodgrps7 { get; set; }
        public bool QnChrFoodgrps8 { get; set; }
        public bool QnChrFoodgrps9 { get; set; }
        public bool QnChrFoodgrps10 { get; set; }
        public bool QnChrFoodgrps11 { get; set; }
        public bool QnChrFoodgrps12 { get; set; }
        public bool QnChrFoodgrps13 { get; set; }
        public bool QnChrFoodgrps14 { get; set; }
        public bool QnChrFoodgrps15 { get; set; }
        public string QnWomenFoodgrpsWomen { get; set; }
        public bool QnWomenFoodgrpsWomen1 { get; set; }
        public bool QnWomenFoodgrpsWomen2 { get; set; }
        public bool QnWomenFoodgrpsWomen3 { get; set; }
        public bool QnWomenFoodgrpsWomen4 { get; set; }
        public bool QnWomenFoodgrpsWomen5 { get; set; }
        public bool QnWomenFoodgrpsWomen6 { get; set; }
        public bool QnWomenFoodgrpsWomen7 { get; set; }
        public bool QnWomenFoodgrpsWomen8 { get; set; }
        public bool QnWomenFoodgrpsWomen9 { get; set; }
        public bool QnWomenFoodgrpsWomen10 { get; set; }
        public bool QnWomenFoodgrpsWomen11 { get; set; }
        public string QnLL1 { get; set; }
        public string QnLL2 { get; set; }
        public string QnLL3 { get; set; }
        public string QnLL4 { get; set; }
        public string QnLL5 { get; set; }
        public string QnLL6 { get; set; }
        public bool QnLL61 { get; set; }
        public bool QnLL62 { get; set; }
        public bool QnLL63 { get; set; }
        public bool QnLL64 { get; set; }
        public bool QnLL65 { get; set; }
        public bool QnLL66 { get; set; }
        public string QnLL7 { get; set; }
        public bool QnLL71 { get; set; }
        public bool QnLL72 { get; set; }
        public bool QnLL73 { get; set; }
        public bool QnLL74 { get; set; }
        public bool QnLL75 { get; set; }
        public bool QnLL76 { get; set; }
        public bool QnLL77 { get; set; }
        public string QnLL8 { get; set; }
        public bool QnLL81 { get; set; }
        public bool QnLL82 { get; set; }
        public bool QnLL83 { get; set; }
        public bool QnLL84 { get; set; }
        public string QnMdr1Ackmdr1 { get; set; }
        public string QnMdr1Shocks { get; set; }
        public bool QnMdr1Shocks1 { get; set; }
        public bool QnMdr1Shocks2 { get; set; }
        public bool QnMdr1Shocks3 { get; set; }
        public bool QnMdr1Shocks4 { get; set; }
        public bool QnMdr1Shocks5 { get; set; }
        public bool QnMdr1Shocks6 { get; set; }
        public bool QnMdr1Shocks7 { get; set; }
        public bool QnMdr1Shocks8 { get; set; }
        public bool QnMdr1Shocks9 { get; set; }
        public bool QnMdr1Shocks10 { get; set; }
        public bool QnMdr1Shocks11 { get; set; }
        public bool QnMdr1Shocks12 { get; set; }
        public bool QnMdr1Shocks13 { get; set; }
        public bool QnMdr1Shocks14 { get; set; }
        public bool QnMdr1Shocks15 { get; set; }
        public bool QnMdr1Shocks16 { get; set; }
        public bool QnMdr1Shocks17 { get; set; }
        public bool QnMdr1Shocks18 { get; set; }
        public bool QnMdr1Shocks19 { get; set; }
        public bool QnMdr1Shocks20 { get; set; }
        public bool QnMdr1Shocks21 { get; set; }
        public bool QnMdr1Shocks22 { get; set; }
        public bool QnMdr1Shocks23 { get; set; }
        public bool QnMdr1Shocks24 { get; set; }
        public bool QnMdr1Shocks25 { get; set; }
        public bool QnMdr1Shocks26 { get; set; }
        public string QnMdr1R102a { get; set; }
        public string QnMdr1R103a { get; set; }
        public string QnMdr1R104a { get; set; }
        public string QnMdr1R105a { get; set; }
        public bool QnMdr1R105a1 { get; set; }
        public bool QnMdr1R105a2 { get; set; }
        public bool QnMdr1R105a3 { get; set; }
        public bool QnMdr1R105a4 { get; set; }
        public bool QnMdr1R105a5 { get; set; }
        public bool QnMdr1R105a6 { get; set; }
        public bool QnMdr1R105a7 { get; set; }
        public bool QnMdr1R105a8 { get; set; }
        public bool QnMdr1R105a9 { get; set; }
        public bool QnMdr1R105a10 { get; set; }
        public bool QnMdr1R105a11 { get; set; }
        public bool QnMdr1R105a12 { get; set; }
        public bool QnMdr1R105a13 { get; set; }
        public bool QnMdr1R105a14 { get; set; }
        public bool QnMdr1R105a15 { get; set; }
        public bool QnMdr1R105a16 { get; set; }
        public bool QnMdr1R105a17 { get; set; }
        public bool QnMdr1R105a18 { get; set; }
        public bool QnMdr1R105a19 { get; set; }
        public bool QnMdr1R105a20 { get; set; }
        public bool QnMdr1R105a21 { get; set; }
        public bool QnMdr1R105a22 { get; set; }
        public bool QnMdr1R105a23 { get; set; }
        public bool QnMdr1R105a24 { get; set; }
        public bool QnMdr1R105a25 { get; set; }
        public bool QnMdr1R105a26 { get; set; }
        public bool QnMdr1R105a27 { get; set; }
        public bool QnMdr1R105a28 { get; set; }
        public bool QnMdr1R105a29 { get; set; }
        public bool QnMdr1R105a30 { get; set; }
        public bool QnMdr1R105a31 { get; set; }
        public string QnMdr1R105aOther { get; set; }
        public string QnMdr1R106a { get; set; }
        public string QnMdr1R102b { get; set; }
        public string QnMdr1R103b { get; set; }
        public string QnMdr1R104b { get; set; }
        public string QnMdr1R105b { get; set; }
        public bool QnMdr1R105b1 { get; set; }
        public bool QnMdr1R105b2 { get; set; }
        public bool QnMdr1R105b3 { get; set; }
        public bool QnMdr1R105b4 { get; set; }
        public bool QnMdr1R105b5 { get; set; }
    }
}
