using System;
using System.Collections.Generic;

#nullable disable

namespace USAIDICANBLAZOR.Models
{
    public partial class OnaCgAssessment
    {
        public double Id { get; set; }
        public string Fieldteam { get; set; }
        public string QnIntroStart { get; set; }
        public string QnIntroEnd { get; set; }
        public string QnIntroDeviceid { get; set; }
        public DateTime? QnIntroAssDate { get; set; }
        public string QnIntroLocRegion { get; set; }
        public string QnIntroLocDistrict { get; set; }
        public string QnIntroLocSubcounty { get; set; }
        public string QnIntroLocParish { get; set; }
        public string QnIntroLoc { get; set; }
        public string QnIntroGroupname { get; set; }
        public string QnIntroFormDate { get; set; }
        public string QnIntroContactperson { get; set; }
        public string QnIntroAltcontact1 { get; set; }
        public string QnIntroGrouppost { get; set; }
        public double? QnIntroTel { get; set; }
        public string QnIntroAltcontact2 { get; set; }
        public double? QnIntroMaleyouth { get; set; }
        public double? QnIntroFemaleyouth { get; set; }
        public double? QnIntroMaleadults { get; set; }
        public double? QnIntroFemaleadults { get; set; }
        public string QnGvGrptype { get; set; }
        public string QnGvGrptypeOther { get; set; }
        public string QnGvReason1 { get; set; }
        public string QnGvScheme { get; set; }
        public string QnGvVslaStart { get; set; }
        public string QnGvReason2 { get; set; }
        public double? QnGvContrSeat { get; set; }
        public string QnGvReason3 { get; set; }
        public string QnGvSavScheme { get; set; }
        public string QnAA1 { get; set; }
        public string QnGvContrMem { get; set; }
        public double? QnGvShare { get; set; }
        public string QnAA2 { get; set; }
        public string QnAA3 { get; set; }
        public string QnAA4 { get; set; }
        public int? QnAA5 { get; set; }
        public string QnAA5Other { get; set; }
        public string QnAA6 { get; set; }
        public string QnAA7 { get; set; }
        public string QnAA10 { get; set; }
        public string QnAA8 { get; set; }
        public string QnAA9 { get; set; }
        public string QnAA11 { get; set; }
        public string QnAA12 { get; set; }
        public string QnAA13 { get; set; }
        public string QnAA14 { get; set; }
        public string QnAA15 { get; set; }
        public string QnAA16 { get; set; }
        public string QnBB1 { get; set; }
        public string QnBB2 { get; set; }
        public bool QnBB21 { get; set; }
        public bool QnBB22 { get; set; }
        public bool QnBB23 { get; set; }
        public bool QnBB24 { get; set; }
        public bool QnBB25 { get; set; }
        public bool QnBB26 { get; set; }
        public bool QnBB27 { get; set; }
        public bool QnBB28 { get; set; }
        public bool QnBB29 { get; set; }
        public string QnBB3 { get; set; }
        public string QnBB4 { get; set; }
        public string QnBB5 { get; set; }
        public string QnBB6 { get; set; }
        public string QnBB7 { get; set; }
        public string QnCC1 { get; set; }
        public string QnCC2 { get; set; }
        public string QnCC3 { get; set; }
        public double? QnCC5 { get; set; }
        public double? QnCC6 { get; set; }
        public double? QnCC7 { get; set; }
        public double? QnCC10 { get; set; }
        public double? QnCC8 { get; set; }
        public string QnCC9 { get; set; }
        public double? QnCC10a { get; set; }
        public string QnCCommentLoan { get; set; }
        public double? QnCC11 { get; set; }
        public string QnCOutLoan { get; set; }
        public string QnCPercLoan { get; set; }
        public double? QnCC11a { get; set; }
        public string QnCCommentOust { get; set; }
        public string QnCC12 { get; set; }
        public string QnCOutLoan3 { get; set; }
        public string QnCPercLoan3 { get; set; }
        public double? QnCC13 { get; set; }
        public double? QnCC14 { get; set; }
        public string QnCC15 { get; set; }
        public bool QnCC151 { get; set; }
        public bool QnCC152 { get; set; }
        public bool QnCC153 { get; set; }
        public bool QnCC154 { get; set; }
        public bool QnCC155 { get; set; }
        public bool QnCC156 { get; set; }
        public bool QnCC157 { get; set; }
        public string QnCC16 { get; set; }
        public string QnCC17 { get; set; }
        public string QnCC18 { get; set; }
        public string QnCC19 { get; set; }
        public string QnCC20 { get; set; }
        public string QnDD1 { get; set; }
        public string QnDD2 { get; set; }
        public string QnDD3 { get; set; }
        public string QnDD4 { get; set; }
        public string QnDD5 { get; set; }
        public double? QnDD6 { get; set; }
        public string QnDD7 { get; set; }
        public string QnDD10 { get; set; }
        public string QnDD8 { get; set; }
        public double? QnDD9 { get; set; }
        public string QnDD11 { get; set; }
        public string QnDD12 { get; set; }
        public string QnDD13 { get; set; }
        public string QnDD14 { get; set; }
        public string QnDD15 { get; set; }
        public string QnDD16 { get; set; }
        public double? QnDD17 { get; set; }
        public double? QnDD18 { get; set; }
        public string QnDD19 { get; set; }
        public string QnEE1 { get; set; }
        public string QnEE2 { get; set; }
        public string QnEE3 { get; set; }
        public string QnEE4 { get; set; }
        public string QnEE5 { get; set; }
        public string QnEE6 { get; set; }
        public string QnEE7 { get; set; }
        public string QnEE10 { get; set; }
        public string QnEE8 { get; set; }
        public string QnEE9 { get; set; }
        public string QnEE11 { get; set; }
        public string QnEE12 { get; set; }
        public string QnEE13 { get; set; }
        public bool QnEE131 { get; set; }
        public bool QnEE132 { get; set; }
        public bool QnEE133 { get; set; }
        public bool QnEE134 { get; set; }
        public bool QnEE135 { get; set; }
        public bool QnEE136 { get; set; }
        public bool QnEE137 { get; set; }
        public bool QnEE1310 { get; set; }
        public bool QnEE138 { get; set; }
        public bool QnEE139 { get; set; }
        public bool QnEE1311 { get; set; }
        public string QnEE14 { get; set; }
        public string QnEE15 { get; set; }
        public string QnEE16 { get; set; }
        public string QnEE17 { get; set; }
        public string QnEE18 { get; set; }
        public string QnEE19 { get; set; }
        public string QnEE20 { get; set; }
        public string QnEE22Tech1 { get; set; }
        public string QnEE21 { get; set; }
        public string QnEE22Tech2 { get; set; }
        public string QnEE22Tech3 { get; set; }
        public string QnScorea1 { get; set; }
        public string QnScorea2 { get; set; }
        public string QnScorea3 { get; set; }
        public string QnScorea4 { get; set; }
        public string QnAck2 { get; set; }
        public string QnScorea5 { get; set; }
        public string QnScorea6 { get; set; }
        public string QnComments { get; set; }
        public string QnImage { get; set; }
        public string QnGps { get; set; }
        public double? QnGpsAltitude { get; set; }
        public double? QnGpsLatitude { get; set; }
        public double? QnGpsLongitude { get; set; }
        public double? QnGpsPrecision { get; set; }
        public string MetaInstanceId { get; set; }
        public string Uuid { get; set; }
        public DateTime? SubmissionTime { get; set; }
        public double? Index { get; set; }
        public string ParentTableName { get; set; }
        public double? ParentIndex { get; set; }
        public string Tags { get; set; }
        public string Notes { get; set; }
        public string Version { get; set; }
        public double? Duration { get; set; }
        public string SubmittedBy { get; set; }
        public double? XformId { get; set; }
        public DateTime? LastUpdatedAt { get; set; }
    }
}
