using System;
using System.Collections.Generic;

#nullable disable

namespace USAIDICANBLAZOR.Models
{
    public partial class OnaIcanBaselinePhase1
    {
        public string Ra { get; set; }
        public string AZ2 { get; set; }
        public string AZ3 { get; set; }
        public string ADeviceid { get; set; }
        public string APhonenumber { get; set; }
        public string ARegionRegion { get; set; }
        public string ARegionDistrict { get; set; }
        public string ARegionSubcounty { get; set; }
        public string ARegionParish { get; set; }
        public string ARegion { get; set; }
        public string AHid { get; set; }
        public string AZ6 { get; set; }
        public string AZ7 { get; set; }
        public string AZ8 { get; set; }
        public string QnBSexres { get; set; }
        public double? QnBAge { get; set; }
        public string QnCCNote { get; set; }
        public string QnCC1 { get; set; }
        public string QnCC2 { get; set; }
        public double? QnCC3 { get; set; }
        public string QnCC4 { get; set; }
        public string QnCC4Other { get; set; }
        public string QnCC5 { get; set; }
        public string QnCC6 { get; set; }
        public string QnCC6Other { get; set; }
        public string QnCC7 { get; set; }
        public string QnCC8 { get; set; }
        public string QnCC8Other { get; set; }
        public double? QnCC8a { get; set; }
        public string QnCC9Other { get; set; }
        public double? QnCC10 { get; set; }
        public double? QnCC11 { get; set; }
        public double? QnCC12 { get; set; }
        public double? QnCC13 { get; set; }
        public string QnCLesspri { get; set; }
        public double? QnCC14 { get; set; }
        public string QnCC15 { get; set; }
        public double? QnCC16 { get; set; }
        public double? QnCC17 { get; set; }
        public string QnFFIntro { get; set; }
        public string QnFF1 { get; set; }
        public string QnFF2 { get; set; }
        public string QnFF2Other { get; set; }
        public double? QnFF3 { get; set; }
        public string QnFF4 { get; set; }
        public string QnFF5 { get; set; }
        public string QnFF5Other { get; set; }
        public string QnFF6 { get; set; }
        public string QnFF6Other { get; set; }
        public string QnFF7 { get; set; }
        public string QnFF8 { get; set; }
        public string QnFF9 { get; set; }
        public string QnFF10 { get; set; }
        public string QnFF10Other { get; set; }
        public string QnGGIntro { get; set; }
        public string QnGG1Farming { get; set; }
        public string QnGG2Farming { get; set; }
        public string QnGG3Farming { get; set; }
        public string QnGG4Farming { get; set; }
        public string QnGG5Farming { get; set; }
        public string QnGG6Farming { get; set; }
        public string QnGG7Farming { get; set; }
        public string QnGG8Farming { get; set; }
        public string QnHHIntro { get; set; }
        public string QnHH1 { get; set; }
        public string QnHH2 { get; set; }
        public string QnHH3 { get; set; }
        public bool QnHH31 { get; set; }
        public bool QnHH32 { get; set; }
        public bool QnHH33 { get; set; }
        public bool QnHH34 { get; set; }
        public string QnHH3Other { get; set; }
        public string QnHH4 { get; set; }
        public bool QnHH41 { get; set; }
        public bool QnHH42 { get; set; }
        public bool QnHH43 { get; set; }
        public bool QnHH44 { get; set; }
        public bool QnHH45 { get; set; }
        public bool QnHH46 { get; set; }
        public bool QnHH47 { get; set; }
        public bool QnHH48 { get; set; }
        public bool QnHH49 { get; set; }
        public bool QnHH410 { get; set; }
        public bool QnHH411 { get; set; }
        public bool QnHH412 { get; set; }
        public bool QnHH413 { get; set; }
        public string QnHH4Other { get; set; }
        public string QnHH5 { get; set; }
        public bool QnHH51 { get; set; }
        public bool QnHH52 { get; set; }
        public bool QnHH53 { get; set; }
        public bool QnHH54 { get; set; }
        public bool QnHH55 { get; set; }
        public bool QnHH56 { get; set; }
        public bool QnHH57 { get; set; }
        public bool QnHH58 { get; set; }
        public string QnHH5Other { get; set; }
        public string QnHH6 { get; set; }
        public string QnBabyIIntro { get; set; }
        public string QnBabyBaby1 { get; set; }
        public double? QnBabyAgeBaby { get; set; }
        public string QnBabySexBaby { get; set; }
        public string QnBabyBfBaby { get; set; }
        public double? QnBabyFeedTimes { get; set; }
        public string QnBabySnacks { get; set; }
        public string QnBabyI2 { get; set; }
        public string QnBabyI3a { get; set; }
        public string QnBabyI3b { get; set; }
        public string QnBabyI4 { get; set; }
        public string QnNN1 { get; set; }
        public bool QnNN11 { get; set; }
        public bool QnNN12 { get; set; }
        public bool QnNN13 { get; set; }
        public bool QnNN14 { get; set; }
        public bool QnNN15 { get; set; }
        public bool QnNN16 { get; set; }
        public string QnJJIntro { get; set; }
        public string QnJJ1a { get; set; }
        public string QnJJ1b { get; set; }
        public string QnJJ1c { get; set; }
        public string QnJJ1d { get; set; }
        public double? QnJJ1dAPrecalc { get; set; }
        public string QnJJ1dA { get; set; }
        public string QnJJ1e { get; set; }
        public string QnJJ1eAPrecalc { get; set; }
        public string QnJJ1eA { get; set; }
        public string QnJJ1f { get; set; }
        public string QnJJ1g { get; set; }
        public string QnJJ1gAPrecalc { get; set; }
        public string QnJJ1gA { get; set; }
        public string QnJJ1h { get; set; }
        public string QnJJ1i { get; set; }
        public string QnJJ1j { get; set; }
        public string QnJJ1k { get; set; }
        public string QnJJ1l { get; set; }
        public string QnJJ1l1 { get; set; }
        public string QnJJ1m { get; set; }
        public string QnJJ1n { get; set; }
        public string QnJJ1o { get; set; }
        public string QnJJ1p { get; set; }
        public string QnJJ1q { get; set; }
        public string QnJJ1r { get; set; }
        public string QnJJ1s { get; set; }
        public string QnJJ1t { get; set; }
        public string QnJJ1u { get; set; }
        public string QnJJ1u1 { get; set; }
        public string QnJJ1w { get; set; }
        public string QnJJ1x { get; set; }
        public string QnJJ3 { get; set; }
        public string QnJJ3A { get; set; }
        public double? QnJJ4Precalc { get; set; }
        public string QnJJ4 { get; set; }
        public string QnResPrompt1 { get; set; }
        public string QnKKNote { get; set; }
        public string QnKK1 { get; set; }
        public string QnKK2 { get; set; }
        public string QnKK3 { get; set; }
        public string QnKK4 { get; set; }
        public string QnKK5 { get; set; }
        public string QnKK6 { get; set; }
        public string QnKK7 { get; set; }
        public string QnKK8 { get; set; }
        public string QnKK8a { get; set; }
        public string QnKK9 { get; set; }
        public string QnKK10 { get; set; }
        public string QnKK11 { get; set; }
        public string QnKK111 { get; set; }
        public string QnKK12 { get; set; }
        public string QnKK13 { get; set; }
        public string QnKK14 { get; set; }
        public string QnKK15 { get; set; }
        public string QnKK16 { get; set; }
        public string QnKK17 { get; set; }
        public string QnKK18 { get; set; }
        public string QnKK19 { get; set; }
        public string QnKK20 { get; set; }
        public string QnKK21 { get; set; }
        public string QnKK22 { get; set; }
        public string QnLL1 { get; set; }
        public string QnLL2 { get; set; }
        public string QnLL3 { get; set; }
        public string QnMdr1Ackmdr1 { get; set; }
        public string QnMdr1AckClimate { get; set; }
        public double? QnMdr1R102a { get; set; }
        public string QnMdr1R103a { get; set; }
        public string QnMdr1R104a { get; set; }
        public string QnMdr1R105a { get; set; }
        public string QnMdr1R106a { get; set; }
        public bool QnMdr1R106a1 { get; set; }
        public bool QnMdr1R106a2 { get; set; }
        public bool QnMdr1R106a3 { get; set; }
        public bool QnMdr1R106a4 { get; set; }
        public bool QnMdr1R106a5 { get; set; }
        public bool QnMdr1R106a6 { get; set; }
        public bool QnMdr1R106a7 { get; set; }
        public bool QnMdr1R106a8 { get; set; }
        public bool QnMdr1R106a9 { get; set; }
        public bool QnMdr1R106a10 { get; set; }
        public bool QnMdr1R106a11 { get; set; }
        public bool QnMdr1R106a12 { get; set; }
        public bool QnMdr1R106a13 { get; set; }
        public bool QnMdr1R106a14 { get; set; }
        public bool QnMdr1R106a15 { get; set; }
        public bool QnMdr1R106a16 { get; set; }
        public bool QnMdr1R106a17 { get; set; }
        public bool QnMdr1R106a18 { get; set; }
        public bool QnMdr1R106a19 { get; set; }
        public bool QnMdr1R106a20 { get; set; }
        public bool QnMdr1R106a21 { get; set; }
        public bool QnMdr1R106a22 { get; set; }
        public bool QnMdr1R106a23 { get; set; }
        public bool QnMdr1R106a24 { get; set; }
        public bool QnMdr1R106a25 { get; set; }
        public bool QnMdr1R106a26 { get; set; }
        public bool QnMdr1R106a27 { get; set; }
        public bool QnMdr1R106a28 { get; set; }
        public bool QnMdr1R106a29 { get; set; }
        public bool QnMdr1R106a30 { get; set; }
        public bool QnMdr1R106a31 { get; set; }
        public string QnMdr1R106aOther { get; set; }
        public string QnMdr1R107a { get; set; }
        public double? QnMdr1R102b { get; set; }
        public string QnMdr1R103b { get; set; }
        public string QnMdr1R104b { get; set; }
        public string QnMdr1R105b { get; set; }
        public string QnMdr1R106b { get; set; }
        public bool QnMdr1R106b1 { get; set; }
        public bool QnMdr1R106b2 { get; set; }
        public bool QnMdr1R106b3 { get; set; }
        public bool QnMdr1R106b4 { get; set; }
        public bool QnMdr1R106b5 { get; set; }
        public bool QnMdr1R106b6 { get; set; }
        public bool QnMdr1R106b7 { get; set; }
        public bool QnMdr1R106b8 { get; set; }
        public bool QnMdr1R106b9 { get; set; }
        public bool QnMdr1R106b10 { get; set; }
        public bool QnMdr1R106b11 { get; set; }
        public bool QnMdr1R106b12 { get; set; }
        public bool QnMdr1R106b13 { get; set; }
        public bool QnMdr1R106b14 { get; set; }
        public bool QnMdr1R106b15 { get; set; }
        public bool QnMdr1R106b16 { get; set; }
        public bool QnMdr1R106b17 { get; set; }
        public bool QnMdr1R106b18 { get; set; }
        public bool QnMdr1R106b19 { get; set; }
        public bool QnMdr1R106b20 { get; set; }
        public bool QnMdr1R106b21 { get; set; }
        public bool QnMdr1R106b22 { get; set; }
        public bool QnMdr1R106b23 { get; set; }
        public bool QnMdr1R106b24 { get; set; }
        public bool QnMdr1R106b25 { get; set; }
        public bool QnMdr1R106b26 { get; set; }
        public bool QnMdr1R106b27 { get; set; }
        public bool QnMdr1R106b28 { get; set; }
        public bool QnMdr1R106b29 { get; set; }
    }
}
