using System;
using System.Collections.Generic;

#nullable disable

namespace USAIDICANBLAZOR.Models
{
    public partial class OnaIbs2020
    {
        public double Id { get; set; }
        public string District { get; set; }
        public string Subcounty { get; set; }
        public string Village { get; set; }
        public string LocationGroupid { get; set; }
        public string LocationGroupname { get; set; }
        public string Ra { get; set; }
        public string AZ6 { get; set; }
        public string AZ7 { get; set; }
        public string AZ8 { get; set; }
        public string QnZ4 { get; set; }
        public string QnStart { get; set; }
        public string QnBSexres { get; set; }
        public double? QnBAge { get; set; }
        public string QnCCNote { get; set; }
        public string QnCC1 { get; set; }
        public string QnCC2 { get; set; }
        public double? QnCC3 { get; set; }
        public string QnCC4 { get; set; }
        public string QnCC4Other { get; set; }
        public string QnCC5 { get; set; }
        public string QnCC6 { get; set; }
        public string QnCC6Other { get; set; }
        public double? QnProfileC7 { get; set; }
        public double? QnProfileC8 { get; set; }
        public double? QnProfileC9 { get; set; }
        public double? QnProfileC10 { get; set; }
        public double? QnProfileC11 { get; set; }
        public double? QnProfileC12 { get; set; }
        public string QnProfileC15 { get; set; }
        public string QnProfileC151 { get; set; }
        public string QnProfileC152 { get; set; }
        public string QnProfileC153 { get; set; }
        public string QnProfileC154 { get; set; }
        public string QnProfileC155 { get; set; }
        public string QnProfileC156 { get; set; }
        public double? QnProfileC15a { get; set; }
        public string QnProfileC15a1 { get; set; }
        public string QnProfileC15a11 { get; set; }
        public string QnProfileC15a12 { get; set; }
        public string QnProfileC15a13 { get; set; }
        public string QnProfileC15a14 { get; set; }
        public string QnProfileC15a15 { get; set; }
        public string QnProfileC15a16 { get; set; }
        public string QnProfileC15a17 { get; set; }
        public string QnProfileC15a18 { get; set; }
        public string QnProfileC15a19 { get; set; }
        public string QnProfileC15a110 { get; set; }
        public string QnProfileC15a111 { get; set; }
        public string QnProfileC15a112 { get; set; }
        public string QnProfileC15a113 { get; set; }
        public string QnProfileC15a114 { get; set; }
        public string QnProfileC15a115 { get; set; }
        public string QnProfileC15a116 { get; set; }
        public double? QnProfileC15b { get; set; }
        public string QnProfileC15b1 { get; set; }
        public string QnProfileC15b11 { get; set; }
        public string QnProfileC15b12 { get; set; }
        public string QnProfileC15b13 { get; set; }
        public string QnProfileC15b14 { get; set; }
        public string QnProfileC15b15 { get; set; }
        public string QnProfileC15b16 { get; set; }
        public string QnProfileC15b17 { get; set; }
        public string QnProfileC15b18 { get; set; }
        public string QnProfileC15b19 { get; set; }
        public string QnProfileC15b110 { get; set; }
        public string QnProfileC15b111 { get; set; }
        public string QnProfileC15b112 { get; set; }
        public string QnProfileC15b113 { get; set; }
        public string QnProfileC15b114 { get; set; }
        public string QnProfileC15b115 { get; set; }
        public string QnProfileC15b116 { get; set; }
        public string QnProfileC15c { get; set; }
        public string QnProfileC15c1 { get; set; }
        public string QnProfileC15c11 { get; set; }
        public string QnProfileC15c12 { get; set; }
        public string QnProfileC15c13 { get; set; }
        public string QnProfileC15c14 { get; set; }
        public string QnProfileC15c15 { get; set; }
        public string QnProfileC15c16 { get; set; }
        public string QnProfileC15c17 { get; set; }
        public string QnProfileC15c18 { get; set; }
        public string QnProfileC15c19 { get; set; }
        public string QnProfileC15c110 { get; set; }
        public string QnProfileC15c111 { get; set; }
        public string QnProfileC15c112 { get; set; }
        public string QnProfileC15c113 { get; set; }
        public string QnProfileC15c114 { get; set; }
        public string QnProfileC15c115 { get; set; }
        public string QnProfileC15c116 { get; set; }
        public string QnProfileC16 { get; set; }
        public string QnProfileC161 { get; set; }
        public string QnProfileC162 { get; set; }
        public string QnProfileC163 { get; set; }
        public string QnProfileC164 { get; set; }
        public string QnProfileC165 { get; set; }
        public string QnProfileC166 { get; set; }
        public string QnProfileC167 { get; set; }
        public string QnProfileC168 { get; set; }
        public string QnProfileC169 { get; set; }
        public string QnProfileC1610 { get; set; }
        public string QnProfileC1611 { get; set; }
        public string QnProfileC1612 { get; set; }
        public string QnProfileC1613 { get; set; }
        public string QnProfileC1614 { get; set; }
        public string QnProfileC1615 { get; set; }
        public string QnProfileC1616 { get; set; }
        public string QnProfileOtherc16 { get; set; }
        public string QnProfileC13 { get; set; }
        public string QnProfileC14 { get; set; }
        public string QnFFIntro { get; set; }
        public string QnFF1 { get; set; }
        public double? QnFF1a { get; set; }
        public double? QnFF2 { get; set; }
        public string QnFF3 { get; set; }
        public double? QnFF5 { get; set; }
        public string QnFF6 { get; set; }
        public string QnFF7 { get; set; }
        public string QnFF71 { get; set; }
        public string QnFF72 { get; set; }
        public string QnFF73 { get; set; }
        public string QnFF729 { get; set; }
        public string QnFF74 { get; set; }
        public string QnFF75 { get; set; }
        public string QnFF76 { get; set; }
        public string QnFF77 { get; set; }
        public string QnFF78 { get; set; }
        public string QnFF79 { get; set; }
        public string QnFF710 { get; set; }
        public string QnFF711 { get; set; }
        public string QnFF712 { get; set; }
        public string QnFF713 { get; set; }
        public string QnFF714 { get; set; }
        public string QnFF715 { get; set; }
        public string QnFF716 { get; set; }
        public string QnFF717 { get; set; }
        public string QnFF718 { get; set; }
        public string QnFF719 { get; set; }
        public string QnFF720 { get; set; }
        public string QnFF721 { get; set; }
        public string QnFF722 { get; set; }
        public string QnFF723 { get; set; }
        public string QnFF724 { get; set; }
        public string QnFF725 { get; set; }
        public string QnFF726 { get; set; }
        public string QnFF727 { get; set; }
        public string QnFF728 { get; set; }
        public string QnFF8 { get; set; }
        public string QnFF81 { get; set; }
        public string QnFF82 { get; set; }
        public string QnFF83 { get; set; }
        public string QnFF84 { get; set; }
        public string QnFF85 { get; set; }
        public string QnFF86 { get; set; }
        public string QnFF87 { get; set; }
        public string QnFF88 { get; set; }
        public string QnFF89 { get; set; }
        public string QnFF9 { get; set; }
        public string QnFF10 { get; set; }
        public string QnFF11 { get; set; }
        public string QnFF12 { get; set; }
        public string QnFF13 { get; set; }
        public string QnFF14 { get; set; }
        public string QnFF15 { get; set; }
        public string QnFF151 { get; set; }
        public string QnFF152 { get; set; }
        public string QnFF153 { get; set; }
        public string QnFF154 { get; set; }
        public string QnFF155 { get; set; }
        public string QnFF156 { get; set; }
        public string QnFF157 { get; set; }
        public string QnFF158 { get; set; }
        public string QnFF159 { get; set; }
        public string QnFF1510 { get; set; }
        public string QnSecionII1 { get; set; }
        public string QnSecionII7 { get; set; }
        public string QnSecionII71 { get; set; }
        public string QnSecionII72 { get; set; }
        public string QnSecionII73 { get; set; }
        public string QnSecionII74 { get; set; }
        public string QnSecionII75 { get; set; }
        public string QnSecionII76 { get; set; }
        public string QnSecionII77 { get; set; }
        public string QnSecionII2 { get; set; }
        public string QnSecionII2a { get; set; }
        public string QnSecionII5 { get; set; }
        public string QnSecionII6 { get; set; }
        public string QnSecionII8 { get; set; }
        public string QnSecionII9 { get; set; }
        public string QnChrFoodgrps { get; set; }
        public string QnChrFoodgrps1 { get; set; }
        public string QnChrFoodgrps2 { get; set; }
        public string QnChrFoodgrps3 { get; set; }
        public string QnChrFoodgrps4 { get; set; }
        public string QnChrFoodgrps5 { get; set; }
        public string QnChrFoodgrps6 { get; set; }
        public string QnChrFoodgrps7 { get; set; }
        public string QnChrFoodgrps8 { get; set; }
        public string QnChrFoodgrps9 { get; set; }
        public string QnChrFoodgrps10 { get; set; }
        public string QnChrFoodgrps11 { get; set; }
        public string QnChrFoodgrps12 { get; set; }
        public string QnChrFoodgrps13 { get; set; }
        public string QnChrFoodgrps14 { get; set; }
        public string QnChrFoodgrps15 { get; set; }
        public string QnWomenFoodgrpsWomen { get; set; }
        public string QnWomenFoodgrpsWomen1 { get; set; }
        public string QnWomenFoodgrpsWomen2 { get; set; }
        public string QnWomenFoodgrpsWomen3 { get; set; }
        public string QnWomenFoodgrpsWomen4 { get; set; }
        public string QnWomenFoodgrpsWomen5 { get; set; }
        public string QnWomenFoodgrpsWomen6 { get; set; }
        public string QnWomenFoodgrpsWomen7 { get; set; }
        public string QnWomenFoodgrpsWomen8 { get; set; }
        public string QnWomenFoodgrpsWomen9 { get; set; }
        public string QnWomenFoodgrpsWomen10 { get; set; }
        public string QnWomenFoodgrpsWomen11 { get; set; }
        public string QnLL1 { get; set; }
        public string QnLL2 { get; set; }
        public string QnLL3 { get; set; }
        public string QnLL4 { get; set; }
        public string QnLL5 { get; set; }
        public string QnLL6 { get; set; }
        public string QnLL61 { get; set; }
        public string QnLL62 { get; set; }
        public string QnLL63 { get; set; }
        public string QnLL64 { get; set; }
        public string QnLL65 { get; set; }
        public string QnLL66 { get; set; }
        public string QnLL7 { get; set; }
        public string QnLL71 { get; set; }
        public string QnLL72 { get; set; }
        public string QnLL73 { get; set; }
        public string QnLL74 { get; set; }
        public string QnLL75 { get; set; }
        public string QnLL76 { get; set; }
        public string QnLL78 { get; set; }
        public string QnLL77 { get; set; }
        public string QnLL8 { get; set; }
        public string QnLL81 { get; set; }
        public string QnLL82 { get; set; }
        public string QnLL83 { get; set; }
        public string QnLL84 { get; set; }
        public string QnFw1 { get; set; }
        public string QnFw2 { get; set; }
        public string QnFw21 { get; set; }
        public string QnFw22 { get; set; }
        public string QnFw23 { get; set; }
        public string QnFw24 { get; set; }
        public string QnFw25 { get; set; }
        public string QnFw26 { get; set; }
        public string QnFw27 { get; set; }
        public string QnFw28 { get; set; }
        public string QnFw29 { get; set; }
        public string QnFw210 { get; set; }
        public string QnFw211 { get; set; }
        public string QnMdr1Ackmdr1 { get; set; }
        public string QnMdr1Shocks { get; set; }
        public string QnMdr1Shocks1 { get; set; }
        public string QnMdr1Shocks2 { get; set; }
        public string QnMdr1Shocks3 { get; set; }
        public string QnMdr1Shocks4 { get; set; }
        public string QnMdr1Shocks5 { get; set; }
        public string QnMdr1Shocks6 { get; set; }
        public string QnMdr1Shocks7 { get; set; }
        public string QnMdr1Shocks8 { get; set; }
        public string QnMdr1Shocks9 { get; set; }
        public string QnMdr1Shocks10 { get; set; }
        public string QnMdr1Shocks11 { get; set; }
        public string QnMdr1Shocks12 { get; set; }
        public string QnMdr1Shocks13 { get; set; }
        public string QnMdr1Shocks14 { get; set; }
        public string QnMdr1Shocks15 { get; set; }
        public string QnMdr1Shocks16 { get; set; }
        public string QnMdr1Shocks17 { get; set; }
        public string QnMdr1Shocks18 { get; set; }
        public string QnMdr1Shocks19 { get; set; }
        public string QnMdr1Shocks20 { get; set; }
        public string QnMdr1Shocks21 { get; set; }
        public string QnMdr1Shocks22 { get; set; }
        public string QnMdr1Shocks23 { get; set; }
        public string QnMdr1Shocks24 { get; set; }
        public string QnMdr1Shocks25 { get; set; }
        public string QnMdr1Shocks26 { get; set; }
        public string QnMdr1Shocks27 { get; set; }
        public string QnMdr1Shocks28 { get; set; }
        public string QnMdr1Shocks29 { get; set; }
        public string QnMdr1R32a1 { get; set; }
        public string QnMdr1R33a1 { get; set; }
        public string QnMdr1R33a11 { get; set; }
        public string QnMdr1R33a12 { get; set; }
        public string QnMdr1R33a13 { get; set; }
        public string QnMdr1R33a14 { get; set; }
        public string QnMdr1R33a15 { get; set; }
        public string QnMdr1R33a16 { get; set; }
        public string QnMdr1R33a17 { get; set; }
        public string QnMdr1R33a18 { get; set; }
        public string QnMdr1R33a19 { get; set; }
        public string QnMdr1R33a110 { get; set; }
        public string QnMdr1R33a111 { get; set; }
        public string QnMdr1R33a112 { get; set; }
        public string QnMdr1R33a113 { get; set; }
        public string QnMdr1R33a114 { get; set; }
        public string QnMdr1R33a115 { get; set; }
        public string QnMdr1R33a116 { get; set; }
        public string QnMdr1R33a117 { get; set; }
        public string QnMdr1R33a118 { get; set; }
        public string QnMdr1R33a119 { get; set; }
        public string QnMdr1R33a120 { get; set; }
        public string QnMdr1R32a2 { get; set; }
        public string QnMdr1R33a2 { get; set; }
        public string QnMdr1R33a21 { get; set; }
        public string QnMdr1R33a22 { get; set; }
        public string QnMdr1R33a23 { get; set; }
        public string QnMdr1R33a24 { get; set; }
        public string QnMdr1R33a25 { get; set; }
        public string QnMdr1R33a26 { get; set; }
        public string QnMdr1R33a27 { get; set; }
        public string QnMdr1R33a28 { get; set; }
        public string QnMdr1R33a29 { get; set; }
        public string QnMdr1R33a210 { get; set; }
        public string QnMdr1R33a211 { get; set; }
        public string QnMdr1R33a212 { get; set; }
        public string QnMdr1R33a213 { get; set; }
        public string QnMdr1R33a214 { get; set; }
        public string QnMdr1R33a215 { get; set; }
        public string QnMdr1R33a216 { get; set; }
        public string QnMdr1R33a217 { get; set; }
        public string QnMdr1R33a218 { get; set; }
        public string QnMdr1R33a219 { get; set; }
        public string QnMdr1R33a220 { get; set; }
        public string QnMdr1R32a3 { get; set; }
        public string QnMdr1R33a3 { get; set; }
        public string QnMdr1R33a31 { get; set; }
        public string QnMdr1R33a32 { get; set; }
        public string QnMdr1R33a33 { get; set; }
        public string QnMdr1R33a34 { get; set; }
        public string QnMdr1R33a35 { get; set; }
        public string QnMdr1R33a36 { get; set; }
        public string QnMdr1R33a37 { get; set; }
        public string QnMdr1R33a38 { get; set; }
        public string QnMdr1R33a39 { get; set; }
        public string QnMdr1R33a310 { get; set; }
        public string QnMdr1R33a311 { get; set; }
        public string QnMdr1R33a312 { get; set; }
        public string QnMdr1R33a313 { get; set; }
        public string QnMdr1R33a314 { get; set; }
        public string QnMdr1R33a315 { get; set; }
        public string QnMdr1R33a316 { get; set; }
        public string QnMdr1R33a317 { get; set; }
        public string QnMdr1R33a318 { get; set; }
        public string QnMdr1R33a319 { get; set; }
        public string QnMdr1R33a320 { get; set; }
        public string QnMdr1R32a4 { get; set; }
        public string QnMdr1R33a4 { get; set; }
        public string QnMdr1R33a41 { get; set; }
        public string QnMdr1R33a42 { get; set; }
        public string QnMdr1R33a43 { get; set; }
        public string QnMdr1R33a44 { get; set; }
        public string QnMdr1R33a45 { get; set; }
        public string QnMdr1R33a46 { get; set; }
        public string QnMdr1R33a47 { get; set; }
        public string QnMdr1R33a48 { get; set; }
        public string QnMdr1R33a49 { get; set; }
        public string QnMdr1R33a410 { get; set; }
        public string QnMdr1R33a411 { get; set; }
        public string QnMdr1R33a412 { get; set; }
        public string QnMdr1R33a413 { get; set; }
        public string QnMdr1R33a414 { get; set; }
        public string QnMdr1R33a415 { get; set; }
        public string QnMdr1R33a416 { get; set; }
        public string QnMdr1R33a417 { get; set; }
        public string QnMdr1R33a418 { get; set; }
        public string QnMdr1R33a419 { get; set; }
        public string QnMdr1R33a420 { get; set; }
        public string QnMdr1R32a5 { get; set; }
        public string QnMdr1R33a5 { get; set; }
        public string QnMdr1R33a51 { get; set; }
        public string QnMdr1R33a52 { get; set; }
        public string QnMdr1R33a53 { get; set; }
        public string QnMdr1R33a54 { get; set; }
        public string QnMdr1R33a55 { get; set; }
        public string QnMdr1R33a56 { get; set; }
        public string QnMdr1R33a57 { get; set; }
        public string QnMdr1R33a58 { get; set; }
        public string QnMdr1R33a59 { get; set; }
        public string QnMdr1R33a510 { get; set; }
        public string QnMdr1R33a511 { get; set; }
        public string QnMdr1R33a512 { get; set; }
        public string QnMdr1R33a513 { get; set; }
        public string QnMdr1R33a514 { get; set; }
        public string QnMdr1R33a515 { get; set; }
        public string QnMdr1R33a516 { get; set; }
        public string QnMdr1R33a517 { get; set; }
        public string QnMdr1R33a518 { get; set; }
        public string QnMdr1R33a519 { get; set; }
        public string QnMdr1R33a520 { get; set; }
        public string QnMdr1R32a6 { get; set; }
        public string QnMdr1R33a6 { get; set; }
        public string QnMdr1R33a61 { get; set; }
        public string QnMdr1R33a62 { get; set; }
        public string QnMdr1R33a63 { get; set; }
        public string QnMdr1R33a64 { get; set; }
        public string QnMdr1R33a65 { get; set; }
        public string QnMdr1R33a66 { get; set; }
        public string QnMdr1R33a67 { get; set; }
        public string QnMdr1R33a68 { get; set; }
        public string QnMdr1R33a69 { get; set; }
        public string QnMdr1R33a610 { get; set; }
        public string QnMdr1R33a611 { get; set; }
        public string QnMdr1R33a612 { get; set; }
        public string QnMdr1R33a613 { get; set; }
        public string QnMdr1R33a614 { get; set; }
        public string QnMdr1R33a615 { get; set; }
        public string QnMdr1R33a616 { get; set; }
        public string QnMdr1R33a617 { get; set; }
        public string QnMdr1R33a618 { get; set; }
        public string QnMdr1R33a619 { get; set; }
        public string QnMdr1R33a620 { get; set; }
        public string QnMdr1R32a7 { get; set; }
        public string QnMdr1R33a7 { get; set; }
        public string QnMdr1R33a71 { get; set; }
        public string QnMdr1R33a72 { get; set; }
        public string QnMdr1R33a73 { get; set; }
        public string QnMdr1R33a74 { get; set; }
        public string QnMdr1R33a75 { get; set; }
        public string QnMdr1R33a76 { get; set; }
        public string QnMdr1R33a77 { get; set; }
        public string QnMdr1R33a78 { get; set; }
        public string QnMdr1R33a79 { get; set; }
        public string QnMdr1R33a710 { get; set; }
        public string QnMdr1R33a711 { get; set; }
        public string QnMdr1R33a712 { get; set; }
        public string QnMdr1R33a713 { get; set; }
        public string QnMdr1R33a714 { get; set; }
        public string QnMdr1R33a715 { get; set; }
        public string QnMdr1R33a716 { get; set; }
        public string QnMdr1R33a717 { get; set; }
        public string QnMdr1R33a718 { get; set; }
        public string QnMdr1R33a719 { get; set; }
        public string QnMdr1R33a720 { get; set; }
        public string QnMdr1R32b1 { get; set; }
        public string QnMdr1R33b1 { get; set; }
        public string QnMdr1R33b11 { get; set; }
        public string QnMdr1R33b12 { get; set; }
        public string QnMdr1R33b13 { get; set; }
        public string QnMdr1R33b14 { get; set; }
        public string QnMdr1R33b15 { get; set; }
        public string QnMdr1R33b16 { get; set; }
        public string QnMdr1R32b2 { get; set; }
        public string QnMdr1R33b2 { get; set; }
        public string QnMdr1R33b21 { get; set; }
        public string QnMdr1R33b22 { get; set; }
        public string QnMdr1R33b23 { get; set; }
        public string QnMdr1R33b24 { get; set; }
        public string QnMdr1R33b25 { get; set; }
        public string QnMdr1R33b26 { get; set; }
        public string QnMdr1R32b3 { get; set; }
        public string QnMdr1R33b3 { get; set; }
        public string QnMdr1R33b31 { get; set; }
        public string QnMdr1R33b32 { get; set; }
        public string QnMdr1R33b33 { get; set; }
        public string QnMdr1R33b34 { get; set; }
        public string QnMdr1R33b35 { get; set; }
        public string QnMdr1R33b36 { get; set; }
        public string QnMdr1R33b37 { get; set; }
        public string QnMdr1R32b4 { get; set; }
        public string QnMdr1R33b4 { get; set; }
        public string QnMdr1R33b41 { get; set; }
        public string QnMdr1R33b42 { get; set; }
        public string QnMdr1R33b43 { get; set; }
        public string QnMdr1R33b44 { get; set; }
        public string QnMdr1R33b45 { get; set; }
        public string QnMdr1R33b46 { get; set; }
        public string QnMdr1R33b47 { get; set; }
        public string QnMdr1R32b5 { get; set; }
        public string QnMdr1R33b5 { get; set; }
        public string QnMdr1R33b51 { get; set; }
        public string QnMdr1R33b52 { get; set; }
        public string QnMdr1R33b53 { get; set; }
        public string QnMdr1R33b54 { get; set; }
        public string QnMdr1R33b55 { get; set; }
        public string QnMdr1R33b56 { get; set; }
        public string QnMdr1R33b57 { get; set; }
        public string QnMdr1R32b6 { get; set; }
        public string QnMdr1R33b6 { get; set; }
        public string QnMdr1R33b61 { get; set; }
        public string QnMdr1R33b62 { get; set; }
        public string QnMdr1R33b63 { get; set; }
        public string QnMdr1R33b64 { get; set; }
        public string QnMdr1R33b65 { get; set; }
        public string QnMdr1R33b66 { get; set; }
        public string QnMdr1R33b67 { get; set; }
        public string QnMdr1R32b7 { get; set; }
        public string QnMdr1R33b7 { get; set; }
        public string QnMdr1R33b71 { get; set; }
        public string QnMdr1R33b72 { get; set; }
        public string QnMdr1R33b73 { get; set; }
        public string QnMdr1R33b74 { get; set; }
        public string QnMdr1R33b75 { get; set; }
        public string QnMdr1R33b76 { get; set; }
        public string QnMdr1R33b77 { get; set; }
        public string QnMdr1R32b8 { get; set; }
        public string QnMdr1R33b8 { get; set; }
        public string QnMdr1R33b81 { get; set; }
        public string QnMdr1R33b82 { get; set; }
        public string QnMdr1R33b83 { get; set; }
        public string QnMdr1R33b84 { get; set; }
        public string QnMdr1R33b85 { get; set; }
        public string QnMdr1R33b86 { get; set; }
        public string QnMdr1R33b87 { get; set; }
        public string QnMdr1R32b9 { get; set; }
        public string QnMdr1R33b9 { get; set; }
        public string QnMdr1R33b91 { get; set; }
        public string QnMdr1R33b92 { get; set; }
        public string QnMdr1R33b93 { get; set; }
        public string QnMdr1R33b94 { get; set; }
        public string QnMdr1R33b95 { get; set; }
        public string QnMdr1R33b96 { get; set; }
        public string QnMdr1R32c1 { get; set; }
        public string QnMdr1R33c1 { get; set; }
        public string QnMdr1R33c11 { get; set; }
        public string QnMdr1R33c12 { get; set; }
        public string QnMdr1R33c13 { get; set; }
        public string QnMdr1R33c14 { get; set; }
        public string QnMdr1R33c15 { get; set; }
        public string QnMdr1R33c16 { get; set; }
        public string QnMdr1R33c17 { get; set; }
        public string QnMdr1R33c18 { get; set; }
        public string QnMdr1R32c2 { get; set; }
        public string QnMdr1R33c2 { get; set; }
        public string QnMdr1R33c21 { get; set; }
        public string QnMdr1R33c22 { get; set; }
        public string QnMdr1R33c23 { get; set; }
        public string QnMdr1R33c24 { get; set; }
        public string QnMdr1R33c25 { get; set; }
        public string QnMdr1R33c26 { get; set; }
        public string QnMdr1R33c27 { get; set; }
        public string QnMdr1R33c28 { get; set; }
        public string QnMdr1R32c3 { get; set; }
        public string QnMdr1R33c3 { get; set; }
        public string QnMdr1R33c31 { get; set; }
        public string QnMdr1R33c32 { get; set; }
        public string QnMdr1R33c33 { get; set; }
        public string QnMdr1R33c34 { get; set; }
        public string QnMdr1R33c35 { get; set; }
        public string QnMdr1R33c36 { get; set; }
        public string QnMdr1R33c37 { get; set; }
        public string QnMdr1R33c38 { get; set; }
        public string QnMdr1R32d1 { get; set; }
        public string QnMdr1R33d1 { get; set; }
        public string QnMdr1R33d11 { get; set; }
        public string QnMdr1R33d12 { get; set; }
        public string QnMdr1R33d13 { get; set; }
        public string QnMdr1R33d14 { get; set; }
        public string QnMdr1R33d15 { get; set; }
        public string QnMdr1R33d16 { get; set; }
        public string QnMdr1R33d17 { get; set; }
        public string QnMdr1R33d18 { get; set; }
        public string QnMdr1R33d19 { get; set; }
        public string QnMdr1R33d110 { get; set; }
        public string QnMdr1R32d2 { get; set; }
        public string QnMdr1R33d2 { get; set; }
        public string QnMdr1R33d21 { get; set; }
        public string QnMdr1R33d22 { get; set; }
        public string QnMdr1R33d23 { get; set; }
        public string QnMdr1R33d24 { get; set; }
        public string QnMdr1R33d25 { get; set; }
        public string QnMdr1R33d26 { get; set; }
        public string QnMdr1R33d27 { get; set; }
        public string QnMdr1R33d28 { get; set; }
        public string QnMdr1R33d29 { get; set; }
        public string QnMdr1R33d210 { get; set; }
        public string QnMdr1R32d3 { get; set; }
        public string QnMdr1R33d3 { get; set; }
        public string QnMdr1R33d31 { get; set; }
        public string QnMdr1R33d32 { get; set; }
        public string QnMdr1R33d33 { get; set; }
        public string QnMdr1R33d34 { get; set; }
        public string QnMdr1R33d35 { get; set; }
        public string QnMdr1R33d36 { get; set; }
        public string QnMdr1R33d37 { get; set; }
        public string QnMdr1R33d38 { get; set; }
        public string QnMdr1R33d39 { get; set; }
        public string QnMdr1R33d310 { get; set; }
        public string QnMdr1R32d4 { get; set; }
        public string QnMdr1R33d4 { get; set; }
        public string QnMdr1R33d41 { get; set; }
        public string QnMdr1R33d42 { get; set; }
        public string QnMdr1R33d43 { get; set; }
        public string QnMdr1R33d44 { get; set; }
        public string QnMdr1R33d45 { get; set; }
        public string QnMdr1R33d46 { get; set; }
        public string QnMdr1R33d47 { get; set; }
        public string QnMdr1R33d48 { get; set; }
        public string QnMdr1R33d49 { get; set; }
        public string QnMdr1R33d410 { get; set; }
        public string QnMdr1R32d5 { get; set; }
        public string QnMdr1R33d5 { get; set; }
        public string QnMdr1R33d51 { get; set; }
        public string QnMdr1R33d52 { get; set; }
        public string QnMdr1R33d53 { get; set; }
        public string QnMdr1R33d54 { get; set; }
        public string QnMdr1R33d55 { get; set; }
        public string QnMdr1R33d56 { get; set; }
        public string QnMdr1R33d57 { get; set; }
        public string QnMdr1R33d58 { get; set; }
        public string QnMdr1R33d59 { get; set; }
        public string QnMdr1R33d510 { get; set; }
        public string QnMdr1R32d6 { get; set; }
        public string QnMdr1R33d6 { get; set; }
        public string QnMdr1R33d61 { get; set; }
        public string QnMdr1R33d62 { get; set; }
        public string QnMdr1R33d63 { get; set; }
        public string QnMdr1R33d64 { get; set; }
        public string QnMdr1R33d65 { get; set; }
        public string QnMdr1R33d66 { get; set; }
        public string QnMdr1R33d67 { get; set; }
        public string QnMdr1R33d68 { get; set; }
        public string QnMdr1R33d69 { get; set; }
        public string QnMdr1R33d610 { get; set; }
        public string QnMdr1R32d7 { get; set; }
        public string QnMdr1R33d7 { get; set; }
        public string QnMdr1R33d71 { get; set; }
        public string QnMdr1R33d72 { get; set; }
        public string QnMdr1R33d73 { get; set; }
        public string QnMdr1R33d74 { get; set; }
        public string QnMdr1R33d75 { get; set; }
        public string QnMdr1R33d76 { get; set; }
        public string QnMdr1R33d77 { get; set; }
        public string QnMdr1R33d78 { get; set; }
        public string QnMdr1R33d79 { get; set; }
        public string QnMdr1R33d710 { get; set; }
        public string QnMdr1R32d8 { get; set; }
        public string QnMdr1R33d8 { get; set; }
        public string QnMdr1R33d81 { get; set; }
        public string QnMdr1R33d82 { get; set; }
        public string QnMdr1R33d83 { get; set; }
        public string QnMdr1R33d84 { get; set; }
        public string QnMdr1R33d85 { get; set; }
        public string QnMdr1R33d86 { get; set; }
        public string QnMdr1R33d87 { get; set; }
        public string QnMdr1R33d88 { get; set; }
        public string QnMdr1R33d89 { get; set; }
        public string QnMdr1R33d810 { get; set; }
        public string QnMdr1R33d811 { get; set; }
        public string QnMdr1R33d812 { get; set; }
        public string QnMdr1R32d9 { get; set; }
        public string QnMdr1R33d91 { get; set; }
        public string QnMdr1R33d92 { get; set; }
        public string QnMdr1R33d93 { get; set; }
        public string QnMdr1R33d94 { get; set; }
        public string QnMdr1R33d95 { get; set; }
        public string QnMdr1R33d96 { get; set; }
        public string QnMdr1R33d97 { get; set; }
        public string QnMdr1R33d98 { get; set; }
        public string QnMdr1R33d99 { get; set; }
        public string QnMdr1R33d910 { get; set; }
        public string QnMdr1R33d911 { get; set; }
        public string QnMdr1R108 { get; set; }
        public string QnCovidCovid19 { get; set; }
        public string QnCovidCovid191 { get; set; }
        public string QnCovidCovid192 { get; set; }
        public string QnCovidCovid193 { get; set; }
        public string QnCovidCovid194 { get; set; }
        public string QnCovidCovid195 { get; set; }
        public string QnCovidCovid196 { get; set; }
        public string QnCovidCovid197 { get; set; }
        public string QnCovidCovid198 { get; set; }
        public string QnCovidCovid1 { get; set; }
        public string QnCovidCovid11 { get; set; }
        public string QnCovidCovid12 { get; set; }
        public string QnCovidCovid13 { get; set; }
        public string QnCovidCovid14 { get; set; }
        public string QnCovidCovid15 { get; set; }
        public string QnCovidCovid16 { get; set; }
        public string QnCovidCovid17 { get; set; }
        public string QnCovidCovid18 { get; set; }
        public string QnCovidCovid199 { get; set; }
        public string QnCovidCovid110 { get; set; }
        public string QnCovidCovid111 { get; set; }
        public string QnCovidCovid112 { get; set; }
        public string QnCovidCovid113 { get; set; }
        public string QnCovidCovid114 { get; set; }
        public string QnCovidCovid115 { get; set; }
        public string QnCovidCovid116 { get; set; }
        public string QnCovidCovid117 { get; set; }
        public string QnCovidCovid118 { get; set; }
        public string QnCovidCovid119 { get; set; }
        public string QnCovidCovid120 { get; set; }
        public string QnCovidCovid1a { get; set; }
        public string QnCovidCovid2 { get; set; }
        public string QnCovidCovid21 { get; set; }
        public string QnCovidCovid22 { get; set; }
        public string QnCovidCovid23 { get; set; }
        public string QnCovidCovid24 { get; set; }
        public string QnCovidCovid25 { get; set; }
        public string QnCovidCovid26 { get; set; }
        public string QnCovidCovid27 { get; set; }
        public string QnCovidCovid2a { get; set; }
        public string QnCovidCovid3 { get; set; }
        public string QnCovidCovid31 { get; set; }
        public string QnCovidCovid32 { get; set; }
        public string QnCovidCovid33 { get; set; }
        public string QnCovidCovid34 { get; set; }
        public string QnCovidCovid35 { get; set; }
        public string QnCovidCovid36 { get; set; }
        public string QnCovidCovid37 { get; set; }
        public string QnCovidCovid38 { get; set; }
        public string QnCovidCovid3a { get; set; }
        public string QnCovidCovid4 { get; set; }
        public string QnCovidCovid41 { get; set; }
        public string QnCovidCovid42 { get; set; }
        public string QnCovidCovid43 { get; set; }
        public string QnCovidCovid44 { get; set; }
        public string QnCovidCovid45 { get; set; }
        public string QnCovidCovid46 { get; set; }
        public string QnCovidCovid47 { get; set; }
        public string QnCovidCovid48 { get; set; }
        public string QnCovidCovid49 { get; set; }
        public string QnCovidCovid410 { get; set; }
        public string QnCovidCovid4a { get; set; }
        public string QnCovidCovid5 { get; set; }
        public string QnCovidCovid51 { get; set; }
        public string QnCovidCovid52 { get; set; }
        public string QnCovidCovid53 { get; set; }
        public string QnCovidCovid54 { get; set; }
        public string QnCovidCovid55 { get; set; }
        public string QnCovidCovid56 { get; set; }
        public string QnCovidCovid57 { get; set; }
        public string QnCovidCovid58 { get; set; }
        public string QnCovidCovid59 { get; set; }
        public string QnCovidCovid510 { get; set; }
        public string QnCovidCovid511 { get; set; }
        public string QnCovidCovid5a { get; set; }
        public string QnCovidCovid6 { get; set; }
        public string QnCovidCovid61 { get; set; }
        public string QnCovidCovid62 { get; set; }
        public string QnCovidCovid63 { get; set; }
        public string QnCovidCovid64 { get; set; }
        public string QnCovidCovid65 { get; set; }
        public string QnCovidCovid66 { get; set; }
        public string QnCovidCovid67 { get; set; }
        public string QnCovidCovid68 { get; set; }
        public string QnCovidCovid69 { get; set; }
        public string QnCovidCovid610 { get; set; }
        public string QnCovidCovid611 { get; set; }
        public string QnCovidCovid6a { get; set; }
        public string QnCovidCovid7 { get; set; }
        public string QnCovidCovid71 { get; set; }
        public string QnCovidCovid72 { get; set; }
        public string QnCovidCovid73 { get; set; }
        public string QnCovidCovid74 { get; set; }
        public string QnCovidCovid75 { get; set; }
        public string QnCovidCovid76 { get; set; }
        public string QnCovidCovid77 { get; set; }
        public string QnCovidCovid7a { get; set; }
        public string QnPrepShockAckmdr2 { get; set; }
        public string QnPrepShockShocks2 { get; set; }
        public string QnPrepShockShocks21 { get; set; }
        public string QnPrepShockShocks22 { get; set; }
        public string QnPrepShockShocks23 { get; set; }
        public string QnPrepShockShocks24 { get; set; }
        public string QnPrepShockShocks25 { get; set; }
        public string QnPrepShockShocks26 { get; set; }
        public string QnPrepShockShocks27 { get; set; }
        public string QnPrepShockShocks28 { get; set; }
        public string QnPrepShockShocks29 { get; set; }
        public string QnPrepShockShocks210 { get; set; }
        public string QnPrepShockShocks211 { get; set; }
        public string QnPrepShockShocks212 { get; set; }
        public string QnPrepShockShocks213 { get; set; }
        public string QnPrepShockShocks214 { get; set; }
        public string QnPrepShockShocks215 { get; set; }
        public string QnPrepShockShocks216 { get; set; }
        public string QnPrepShockShocks217 { get; set; }
        public string QnPrepShockShocks218 { get; set; }
        public string QnPrepShockShocks219 { get; set; }
        public string QnPrepShockShocks220 { get; set; }
        public string QnPrepShockShocks221 { get; set; }
        public string QnPrepShockShocks222 { get; set; }
        public string QnPrepShockShocks223 { get; set; }
        public string QnPrepShockShocks224 { get; set; }
        public string QnPrepShockShocks225 { get; set; }
        public string QnPrepShockShocks226 { get; set; }
        public string QnPrepShockShocks227 { get; set; }
        public string QnPrepShockShocks228 { get; set; }
        public string QnPrepShockShocks229 { get; set; }
        public string QnPrepShockR1102a1 { get; set; }
        public string QnPrepShockR1103a1 { get; set; }
        public string QnPrepShockR1103a11 { get; set; }
        public string QnPrepShockR1103a12 { get; set; }
        public string QnPrepShockR1103a13 { get; set; }
        public string QnPrepShockR1103a14 { get; set; }
        public string QnPrepShockR1103a15 { get; set; }
        public string QnPrepShockR1103a16 { get; set; }
        public string QnPrepShockR1103a17 { get; set; }
        public string QnPrepShockR1103a18 { get; set; }
        public string QnPrepShockR1103a19 { get; set; }
        public string QnPrepShockR1103a110 { get; set; }
        public string QnPrepShockR1103a111 { get; set; }
        public string QnPrepShockR1103a112 { get; set; }
        public string QnPrepShockR1103a113 { get; set; }
        public string QnPrepShockR1103a114 { get; set; }
        public string QnPrepShockR1103a115 { get; set; }
        public string QnPrepShockR1103a116 { get; set; }
        public string QnPrepShockR1103a117 { get; set; }
        public string QnPrepShockR1103a118 { get; set; }
        public string QnPrepShockR1103a119 { get; set; }
        public string QnPrepShockR1103a120 { get; set; }
        public string QnPrepShockR1102a2 { get; set; }
        public string QnPrepShockR1103a2 { get; set; }
        public string QnPrepShockR1103a21 { get; set; }
        public string QnPrepShockR1103a22 { get; set; }
        public string QnPrepShockR1103a23 { get; set; }
        public string QnPrepShockR1103a24 { get; set; }
        public string QnPrepShockR1103a25 { get; set; }
        public string QnPrepShockR1103a26 { get; set; }
        public string QnPrepShockR1103a27 { get; set; }
        public string QnPrepShockR1103a28 { get; set; }
        public string QnPrepShockR1103a29 { get; set; }
        public string QnPrepShockR1103a210 { get; set; }
        public string QnPrepShockR1103a211 { get; set; }
        public string QnPrepShockR1103a212 { get; set; }
        public string QnPrepShockR1103a213 { get; set; }
        public string QnPrepShockR1103a214 { get; set; }
        public string QnPrepShockR1103a215 { get; set; }
        public string QnPrepShockR1103a216 { get; set; }
        public string QnPrepShockR1103a217 { get; set; }
        public string QnPrepShockR1103a218 { get; set; }
        public string QnPrepShockR1103a219 { get; set; }
        public string QnPrepShockR1103a220 { get; set; }
        public string QnPrepShockR1102a3 { get; set; }
        public string QnPrepShockR1103a3 { get; set; }
        public string QnPrepShockR1103a31 { get; set; }
        public string QnPrepShockR1103a32 { get; set; }
        public string QnPrepShockR1103a33 { get; set; }
        public string QnPrepShockR1103a34 { get; set; }
        public string QnPrepShockR1103a35 { get; set; }
        public string QnPrepShockR1103a36 { get; set; }
        public string QnPrepShockR1103a37 { get; set; }
        public string QnPrepShockR1103a38 { get; set; }
        public string QnPrepShockR1103a39 { get; set; }
        public string QnPrepShockR1103a310 { get; set; }
        public string QnPrepShockR1103a311 { get; set; }
        public string QnPrepShockR1103a312 { get; set; }
        public string QnPrepShockR1103a313 { get; set; }
        public string QnPrepShockR1103a314 { get; set; }
        public string QnPrepShockR1103a315 { get; set; }
        public string QnPrepShockR1103a316 { get; set; }
        public string QnPrepShockR1103a317 { get; set; }
        public string QnPrepShockR1103a318 { get; set; }
        public string QnPrepShockR1103a319 { get; set; }
        public string QnPrepShockR1103a320 { get; set; }
        public string QnPrepShockR1102a4 { get; set; }
        public string QnPrepShockR1103a4 { get; set; }
        public string QnPrepShockR1103a41 { get; set; }
        public string QnPrepShockR1103a42 { get; set; }
        public string QnPrepShockR1103a43 { get; set; }
        public string QnPrepShockR1103a44 { get; set; }
        public string QnPrepShockR1103a45 { get; set; }
        public string QnPrepShockR1103a46 { get; set; }
        public string QnPrepShockR1103a47 { get; set; }
        public string QnPrepShockR1103a48 { get; set; }
        public string QnPrepShockR1103a49 { get; set; }
        public string QnPrepShockR1103a410 { get; set; }
        public string QnPrepShockR1103a411 { get; set; }
        public string QnPrepShockR1103a412 { get; set; }
        public string QnPrepShockR1103a413 { get; set; }
        public string QnPrepShockR1103a414 { get; set; }
        public string QnPrepShockR1103a415 { get; set; }
        public string QnPrepShockR1103a416 { get; set; }
        public string QnPrepShockR1103a417 { get; set; }
        public string QnPrepShockR1103a418 { get; set; }
        public string QnPrepShockR1103a419 { get; set; }
        public string QnPrepShockR1103a420 { get; set; }
        public string QnPrepShockR1102a5 { get; set; }
        public string QnPrepShockR1103a5 { get; set; }
        public string QnPrepShockR1103a51 { get; set; }
        public string QnPrepShockR1103a52 { get; set; }
        public string QnPrepShockR1103a53 { get; set; }
        public string QnPrepShockR1103a54 { get; set; }
        public string QnPrepShockR1103a55 { get; set; }
        public string QnPrepShockR1103a56 { get; set; }
        public string QnPrepShockR1103a57 { get; set; }
        public string QnPrepShockR1103a58 { get; set; }
        public string QnPrepShockR1103a59 { get; set; }
        public string QnPrepShockR1103a510 { get; set; }
        public string QnPrepShockR1103a511 { get; set; }
        public string QnEnd { get; set; }
        public string QnAck2 { get; set; }
        public string QnR1909 { get; set; }
        public string QnEnfood { get; set; }
        public string QnEnFood3 { get; set; }
        public string QnR5R501 { get; set; }
        public string QnR5R502 { get; set; }
        public string QnR5R508 { get; set; }
        public string QnComments { get; set; }
        public string QnMr6R601 { get; set; }
        public string QnAckNoteM { get; set; }
        public string QnMdr3R308 { get; set; }
        public string QnMr13R139 { get; set; }
        public string QnMr2R201b { get; set; }
        public string QnMr2R201c { get; set; }
        public string QnMr2R201d { get; set; }
        public string QnMr6R602a { get; set; }
        public string QnSignature { get; set; }
        public string QnMr13R1314 { get; set; }
        public string QnMr13R139a { get; set; }
        public string SubmittedBy { get; set; }
        public string QnMdOtherT1 { get; set; }
        public string QnMdOtherT3 { get; set; }
        public string QnMr2AckMr2 { get; set; }
        public string QnModr14R1403 { get; set; }
        public string QnMr6AckMdr6 { get; set; }
        public string QnWnDecisions { get; set; }
        public string QnMr13AckMd13 { get; set; }
        public string QnR2aLivestock { get; set; }
        public string QnSection9Q900 { get; set; }
        public string QnSection9Q901 { get; set; }
        public string QnWnDecisions6 { get; set; }
        public string ProdAssets { get; set; }
        public string QnSeasonsActivity { get; set; }
        public string LivestockSold { get; set; }
        public string QnMr2ProdAssetsSold { get; set; }
        public string QnPrepShockR1102b2 { get; set; }
        public string QnPrepShockR1102b9 { get; set; }
        public string QnPrepShockR1103b2 { get; set; }
        public string QnPrepShockR1103b9 { get; set; }
        public string QnInfoTrainingInfoT { get; set; }
        public string QnFF7trees { get; set; }
        public string QnR5AckR5 { get; set; }
        public string QnMdOtherT4 { get; set; }
        public string QnMdOtherT5 { get; set; }
        public string QnProfileC15x { get; set; }
        public string QnSectionRMis { get; set; }
        public string QnProfileC15x1 { get; set; }
        public string QnR2aLivestockSold { get; set; }
        public string QnSection9Q902 { get; set; }
        public string QnProfileLesspri { get; set; }
        public DateTime? SubmissionTime { get; set; }
        public string QnRankingRSrcIncome1 { get; set; }
        public string QnRankingRSrcIncome11 { get; set; }
        public string QnZ4Altitude { get; set; }
        public string QnZ4Precision { get; set; }
        public string QnFCrp1 { get; set; }
        public string QnMr13R137 { get; set; }
        public double? QnZ4Latitude { get; set; }
        public double? QnZ4Longitude { get; set; }
        public DateTime? LastUpdatedAt { get; set; }
    }
}
