using System;
using System.Collections.Generic;

#nullable disable

namespace USAIDICANBLAZOR.Models
{
    public partial class OnaMiycanMonthlySummaryVer4
    {
        public double Id { get; set; }
        public string Start { get; set; }
        public string Endd { get; set; }
        public string Deviceid { get; set; }
        public string District { get; set; }
        public string Groupid { get; set; }
        public string Subcounty { get; set; }
        public string Village { get; set; }
        public string Groupname { get; set; }
        public string Fo { get; set; }
        public string CalcYr { get; set; }
        public string CurrYr { get; set; }
        public string CurrMth { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string VhtFname { get; set; }
        public string VhtLname { get; set; }
        public string Mod { get; set; }
        public string Mod1 { get; set; }
        public double? Mod11 { get; set; }
        public double? Mod12 { get; set; }
        public double? Mod13 { get; set; }
        public double? Mod14 { get; set; }
        public double? Mod15 { get; set; }
        public double? Mod16 { get; set; }
        public double? Mod17 { get; set; }
        public double? Mod110 { get; set; }
        public double? Mod18 { get; set; }
        public double? Mod19 { get; set; }
        public double? Mod111 { get; set; }
        public string Mod2 { get; set; }
        public double? Mod21 { get; set; }
        public double? Mod22 { get; set; }
        public double? Mod23 { get; set; }
        public double? Mod24 { get; set; }
        public string Mod3 { get; set; }
        public double? Mod31 { get; set; }
        public double? Mod32 { get; set; }
        public double? Mod33 { get; set; }
        public double? Mod34 { get; set; }
        public double? Mod35 { get; set; }
        public double? Mod36 { get; set; }
        public double? Mod37 { get; set; }
        public string Mod4 { get; set; }
        public double? Mod41 { get; set; }
        public double? Mod42 { get; set; }
        public double? Mod43 { get; set; }
        public double? Mod44 { get; set; }
        public double? Mod45 { get; set; }
        public double? Mod46 { get; set; }
        public double? L19 { get; set; }
        public double? P19 { get; set; }
        public double? PA19 { get; set; }
        public double? LA19 { get; set; }
        public double? O19f { get; set; }
        public double? O19m { get; set; }
        public double? OA19m { get; set; }
        public double? OA19f { get; set; }
        public string Alll { get; set; }
        public string PregMothers { get; set; }
        public string LacMothers { get; set; }
        public string OtherM { get; set; }
        public string OtherF { get; set; }
        public double? MaleChilddeath { get; set; }
        public double? FemaleChilddeath { get; set; }
        public double? MothersDead { get; set; }
        public double? ScrMale { get; set; }
        public double? ScrFemale { get; set; }
        public double? ScrMale2 { get; set; }
        public double? ScrFemale2 { get; set; }
        public double? YellowMale5 { get; set; }
        public double? YellowFemale5 { get; set; }
        public double? YellowMale2 { get; set; }
        public double? YellowFemale2 { get; set; }
        public double? RedMale5 { get; set; }
        public double? RedFemale5 { get; set; }
        public double? RedMale2 { get; set; }
        public double? RedFemale2 { get; set; }
        public string Scr { get; set; }
        public string Referrals { get; set; }
        public double? Referrals1 { get; set; }
        public double? Referrals2 { get; set; }
        public double? Referrals3 { get; set; }
        public string Otheref { get; set; }
        public double? Referrals4 { get; set; }
        public double? Referrals5 { get; set; }
        public string NumAnc { get; set; }
        public string NumFp { get; set; }
        public string Comments { get; set; }
        public string NumMal { get; set; }
        public string NumOther { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public string Image { get; set; }
        public string Ack2 { get; set; }
        public string InstanceId { get; set; }
        public string Uuid { get; set; }
        public DateTime? SubmissionTime { get; set; }
        public double? Index { get; set; }
        public string ParentTableName { get; set; }
        public double? ParentIndex { get; set; }
        public string Tags { get; set; }
        public string Notes { get; set; }
        public string Version { get; set; }
        public double? Duration { get; set; }
        public string SubmittedBy { get; set; }
        public double? XformId { get; set; }
        public DateTime? LastUpdatedAt { get; set; }
    }
}
