using System;
using System.Collections.Generic;

#nullable disable

namespace USAIDICANBLAZOR.Models
{
    public partial class OnaMiycanMonthlySummaryVer5
    {
        public double Id { get; set; }
        public string Start { get; set; }
        public string Endd { get; set; }
        public string Deviceid { get; set; }
        public string District { get; set; }
        public string Subcounty { get; set; }
        public string Village { get; set; }
        public string LocationGroupid { get; set; }
        public string LocationGroupname { get; set; }
        public string VhtId { get; set; }
        public string Fo { get; set; }
        public string CalcYr { get; set; }
        public string CurrYr { get; set; }
        public string CurrMth { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Mod { get; set; }
        public string Mod1 { get; set; }
        public double? Mod11 { get; set; }
        public double? Mod12 { get; set; }
        public double? Mod13 { get; set; }
        public double? Mod14 { get; set; }
        public double? Mod15 { get; set; }
        public double? Mod16 { get; set; }
        public double? Mod17 { get; set; }
        public double? Mod110 { get; set; }
        public double? Mod18 { get; set; }
        public double? Mod19 { get; set; }
        public double? Mod111 { get; set; }
        public string Mod2 { get; set; }
        public string Mod21 { get; set; }
        public string Mod22 { get; set; }
        public string Mod23 { get; set; }
        public string Mod24 { get; set; }
        public string Mod25 { get; set; }
        public string Mod26 { get; set; }
        public string Mod27 { get; set; }
        public string Mod28 { get; set; }
        public string Mod3 { get; set; }
        public string Mod31 { get; set; }
        public string Mod32 { get; set; }
        public string Mod33 { get; set; }
        public string Mod34 { get; set; }
        public string Mod35 { get; set; }
        public string Mod36 { get; set; }
        public string Mod37 { get; set; }
        public string Mod4 { get; set; }
        public double? Mod41 { get; set; }
        public double? Mod42 { get; set; }
        public double? Mod43 { get; set; }
        public double? Mod44 { get; set; }
        public double? Mod45 { get; set; }
        public double? Mod46 { get; set; }
        public string Mod5 { get; set; }
        public string Mod51 { get; set; }
        public string Mod6 { get; set; }
        public string Mod61 { get; set; }
        public string Mod62 { get; set; }
        public double? MothP19 { get; set; }
        public double? MothPA19 { get; set; }
        public double? MothL19 { get; set; }
        public double? MothLA19 { get; set; }
        public double? OthO19m { get; set; }
        public double? OthO19f { get; set; }
        public double? OthOA19m { get; set; }
        public double? OthOA19f { get; set; }
        public string All { get; set; }
        public string PregMothers { get; set; }
        public string LacMothers { get; set; }
        public string OtherM { get; set; }
        public string OtherF { get; set; }
        public double? MuacScrFemale { get; set; }
        public double? MuacScrMale { get; set; }
        public double? MuacYellowFemale5 { get; set; }
        public double? MuacYellowMale5 { get; set; }
        public double? MuacRedFemale5 { get; set; }
        public double? MuacRedMale5 { get; set; }
        public string MuacScr { get; set; }
        public double? OdemaNoOdemaF { get; set; }
        public double? OdemaNoOdemaM { get; set; }
        public double? OdemaOdemaF { get; set; }
        public double? OdemaOdemaM { get; set; }
        public double? OdemaOdemaplus2F { get; set; }
        public double? OdemaOdemaplus2M { get; set; }
        public double? OdemaOdemaplus3F { get; set; }
        public double? OdemaOdemaplus3M { get; set; }
        public double? OdemaVitaF { get; set; }
        public double? OdemaVitaM { get; set; }
        public string Referrals { get; set; }
        public double? Referrals1 { get; set; }
        public double? Referrals2 { get; set; }
        public double? Referrals3 { get; set; }
        public bool? Referrals6 { get; set; }
        public bool? Referrals4 { get; set; }
        public bool? Referrals5 { get; set; }
        public string Otheref { get; set; }
        public double? NumAnc { get; set; }
        public double? NumFp { get; set; }
        public double? NumMal { get; set; }
        public string NumVita { get; set; }
        public double? NumOther { get; set; }
        public string Comments { get; set; }
        public string Image { get; set; }
        public string Ack2 { get; set; }
        public string MetaInstanceId { get; set; }
        public string Uuid { get; set; }
        public DateTime? SubmissionTime { get; set; }
        public double? Index { get; set; }
        public string ParentTableName { get; set; }
        public double? ParentIndex { get; set; }
        public string Tags { get; set; }
        public string Notes { get; set; }
        public string Version { get; set; }
        public double? Duration { get; set; }
        public string SubmittedBy { get; set; }
        public double? XformId { get; set; }
        public DateTime? LastUpdatedAt { get; set; }
    }
}
