using System;
using System.Collections.Generic;

#nullable disable

namespace USAIDICANBLAZOR.Models
{
    public partial class OnaRms1
    {
        public double Id { get; set; }
        public string District { get; set; }
        public string Subcounty { get; set; }
        public string Village { get; set; }
        public string LocationGroupid { get; set; }
        public string LocationGroupname { get; set; }
        public string Ra { get; set; }
        public string AZ6 { get; set; }
        public string AZ7 { get; set; }
        public string AZ8 { get; set; }
        public string QnQn11 { get; set; }
        public double? QnQn121 { get; set; }
        public string QnQn13 { get; set; }
        public string QnQn14 { get; set; }
        public string QnQn15 { get; set; }
        public string QnOtherQn15 { get; set; }
        public string QnQn16 { get; set; }
        public double? QnQn16Seasons { get; set; }
        public double? QnQn16Times { get; set; }
        public double? QnSectioncQn21 { get; set; }
        public string QnSectioncQn22 { get; set; }
        public double? QnSectioncQn221 { get; set; }
        public string QnSectioncQn23 { get; set; }
        public bool? QnSectioncQn231 { get; set; }
        public bool? QnSectioncQn232 { get; set; }
        public bool? QnSectioncQn233 { get; set; }
        public bool? QnSectioncQn234 { get; set; }
        public bool? QnSectioncQn235 { get; set; }
        public bool? QnSectioncQn236 { get; set; }
        public bool? QnSectioncQn237 { get; set; }
        public bool? QnSectioncQn238 { get; set; }
        public bool? QnSectioncQn239 { get; set; }
        public string QnSectioncOtherQn23 { get; set; }
        public string QnSectioncQn231Main { get; set; }
        public bool? QnSectioncQn2311 { get; set; }
        public bool? QnSectioncQn2312 { get; set; }
        public bool? QnSectioncQn2313 { get; set; }
        public bool? QnSectioncQn2314 { get; set; }
        public bool? QnSectioncQn2315 { get; set; }
        public bool? QnSectioncQn2316 { get; set; }
        public bool? QnSectioncQn2317 { get; set; }
        public string QnSectioncOtherWhyNo { get; set; }
        public double? QnSectioncQn24 { get; set; }
        public string QnSectioncQn25 { get; set; }
        public bool? QnSectioncQn251 { get; set; }
        public bool? QnSectioncQn252 { get; set; }
        public bool? QnSectioncQn253 { get; set; }
        public bool? QnSectioncQn254 { get; set; }
        public bool? QnSectioncQn255 { get; set; }
        public bool? QnSectioncQn256 { get; set; }
        public bool? QnSectioncQn257 { get; set; }
        public bool? QnSectioncQn258 { get; set; }
        public bool? QnSectioncQn259 { get; set; }
        public bool? QnSectioncQn2510 { get; set; }
        public string QnSectioncQn251Main { get; set; }
        public bool? QnSectioncQn2511 { get; set; }
        public bool? QnSectioncQn2512 { get; set; }
        public bool? QnSectioncQn2513 { get; set; }
        public bool? QnSectioncQn2514 { get; set; }
        public bool? QnSectioncQn2515 { get; set; }
        public bool? QnSectioncQn2516 { get; set; }
        public bool? QnSectioncQn2517 { get; set; }
        public bool? QnSectioncQn2518 { get; set; }
        public string QnSectioncQn252Main { get; set; }
        public bool? QnSectioncQn2521 { get; set; }
        public bool? QnSectioncQn2522 { get; set; }
        public bool? QnSectioncQn2523 { get; set; }
        public bool? QnSectioncQn2524 { get; set; }
        public bool? QnSectioncQn2525 { get; set; }
        public bool? QnSectioncQn2526 { get; set; }
        public bool? QnSectioncQn2527 { get; set; }
        public bool? QnSectioncQn2528 { get; set; }
        public string QnSectioncQn253Main { get; set; }
        public bool? QnSectioncQn2531 { get; set; }
        public bool? QnSectioncQn2532 { get; set; }
        public bool? QnSectioncQn2533 { get; set; }
        public bool? QnSectioncQn2534 { get; set; }
        public bool? QnSectioncQn2535 { get; set; }
        public bool? QnSectioncQn2536 { get; set; }
        public bool? QnSectioncQn2537 { get; set; }
        public bool? QnSectioncQn2538 { get; set; }
        public string QnSectioncQn254Main { get; set; }
        public bool? QnSectioncQn2541 { get; set; }
        public bool? QnSectioncQn2542 { get; set; }
        public bool? QnSectioncQn2543 { get; set; }
        public bool? QnSectioncQn2544 { get; set; }
        public bool? QnSectioncQn2545 { get; set; }
        public bool? QnSectioncQn2546 { get; set; }
        public bool? QnSectioncQn2547 { get; set; }
        public bool? QnSectioncQn2548 { get; set; }
        public string QnSectioncQn255Main { get; set; }
        public bool? QnSectioncQn2551 { get; set; }
        public bool? QnSectioncQn2552 { get; set; }
        public bool? QnSectioncQn2553 { get; set; }
        public bool? QnSectioncQn2554 { get; set; }
        public bool? QnSectioncQn2555 { get; set; }
        public bool? QnSectioncQn2556 { get; set; }
        public bool? QnSectioncQn2557 { get; set; }
        public bool? QnSectioncQn2558 { get; set; }
        public string QnSectioncQn256Main { get; set; }
        public bool? QnSectioncQn2561 { get; set; }
        public bool? QnSectioncQn2562 { get; set; }
        public bool? QnSectioncQn2563 { get; set; }
        public bool? QnSectioncQn2564 { get; set; }
        public bool? QnSectioncQn2565 { get; set; }
        public bool? QnSectioncQn2566 { get; set; }
        public bool? QnSectioncQn2567 { get; set; }
        public bool? QnSectioncQn2568 { get; set; }
        public string QnSectioncQn257Main { get; set; }
        public bool? QnSectioncQn2571 { get; set; }
        public bool? QnSectioncQn2572 { get; set; }
        public bool? QnSectioncQn2573 { get; set; }
        public bool? QnSectioncQn2574 { get; set; }
        public bool? QnSectioncQn2575 { get; set; }
        public bool? QnSectioncQn2576 { get; set; }
        public bool? QnSectioncQn2577 { get; set; }
        public bool? QnSectioncQn2578 { get; set; }
        public string QnSectioncQn258Main { get; set; }
        public bool? QnSectioncQn2581 { get; set; }
        public bool? QnSectioncQn2582 { get; set; }
        public bool? QnSectioncQn2583 { get; set; }
        public bool? QnSectioncQn2584 { get; set; }
        public bool? QnSectioncQn2585 { get; set; }
        public bool? QnSectioncQn2586 { get; set; }
        public bool? QnSectioncQn2587 { get; set; }
        public bool? QnSectioncQn2588 { get; set; }
        public string QnSectioncQn259Main { get; set; }
        public bool? QnSectioncQn2591 { get; set; }
        public bool? QnSectioncQn2592 { get; set; }
        public bool? QnSectioncQn2593 { get; set; }
        public bool? QnSectioncQn2594 { get; set; }
        public bool? QnSectioncQn2595 { get; set; }
        public bool? QnSectioncQn2596 { get; set; }
        public bool? QnSectioncQn2597 { get; set; }
        public bool? QnSectioncQn2598 { get; set; }
        public double? QnSectioncQn27 { get; set; }
        public string QnSectioncQn28 { get; set; }
        public string QnSectioncQn29 { get; set; }
        public bool? QnSectioncQn291 { get; set; }
        public bool? QnSectioncQn292 { get; set; }
        public bool? QnSectioncQn293 { get; set; }
        public bool? QnSectioncQn294 { get; set; }
        public bool? QnSectioncQn295 { get; set; }
        public bool? QnSectioncQn296 { get; set; }
        public bool? QnSectioncQn297 { get; set; }
        public bool? QnSectioncQn298 { get; set; }
        public bool? QnSectioncQn299 { get; set; }
        public bool? QnSectioncQn2910 { get; set; }
        public string QnSectioncOtherSituation { get; set; }
        public double? QnSectioncQn210 { get; set; }
        public string QnSectioncQn211 { get; set; }
        public double? QnSectioncQn212 { get; set; }
        public string QnSectioncQn213 { get; set; }
        public string QnSectioncQn2131 { get; set; }
        public bool? QnSectioncQn21311 { get; set; }
        public bool? QnSectioncQn21312 { get; set; }
        public bool? QnSectioncQn21313 { get; set; }
        public bool? QnSectioncQn21314 { get; set; }
        public bool? QnSectioncQn21315 { get; set; }
        public double? QnSectioncQn216 { get; set; }
        public string QnSectiondShocks { get; set; }
        public bool? QnSectiondShocks1 { get; set; }
        public bool? QnSectiondShocks2 { get; set; }
        public bool? QnSectiondShocks3 { get; set; }
        public bool? QnSectiondShocks4 { get; set; }
        public bool? QnSectiondShocks5 { get; set; }
        public bool? QnSectiondShocks6 { get; set; }
        public bool? QnSectiondShocks7 { get; set; }
        public bool? QnSectiondShocks8 { get; set; }
        public bool? QnSectiondShocks9 { get; set; }
        public bool? QnSectiondShocks10 { get; set; }
        public bool? QnSectiondShocks11 { get; set; }
        public bool? QnSectiondShocks12 { get; set; }
        public bool? QnSectiondShocks13 { get; set; }
        public bool? QnSectiondShocks14 { get; set; }
        public bool? QnSectiondShocks15 { get; set; }
        public bool? QnSectiondShocks16 { get; set; }
        public bool? QnSectiondShocks17 { get; set; }
        public bool? QnSectiondShocks18 { get; set; }
        public bool? QnSectiondShocks19 { get; set; }
        public bool? QnSectiondShocks20 { get; set; }
        public string QnSectiondShocks1Main { get; set; }
        public string QnSectiondShocks2Main { get; set; }
        public string QnSectiondShocks3Main { get; set; }
        public string QnSectiondShocks4Main { get; set; }
        public string QnSectiondShocks5Main { get; set; }
        public string QnSectiondShocks6Main { get; set; }
        public string QnSectiondShocks7Main { get; set; }
        public string QnSectiondShocks8Main { get; set; }
        public string QnSectiondShocks9Main { get; set; }
        public string QnSectiondShocks10Main { get; set; }
        public string QnSectiondShocks11Main { get; set; }
        public string QnSectiondShocks12Main { get; set; }
        public string QnSectiondShocks13Main { get; set; }
        public string QnSectiondShocks14Main { get; set; }
        public string QnSectiondShocks15Main { get; set; }
        public string QnSectiondShocks16Main { get; set; }
        public string QnSectiondShocks17Main { get; set; }
        public string QnSectiondShocks18Main { get; set; }
        public string QnSectiondShocks19Main { get; set; }
        public string QnSectiondCap1 { get; set; }
        public bool? QnSectiondCap11 { get; set; }
        public bool? QnSectiondCap12 { get; set; }
        public bool? QnSectiondCap13 { get; set; }
        public bool? QnSectiondCap14 { get; set; }
        public bool? QnSectiondCap15 { get; set; }
        public bool? QnSectiondCap16 { get; set; }
        public bool? QnSectiondCap17 { get; set; }
        public bool? QnSectiondCap18 { get; set; }
        public bool? QnSectiondCap19 { get; set; }
        public bool? QnSectiondCap110 { get; set; }
        public bool? QnSectiondCap111 { get; set; }
        public bool? QnSectiondCap112 { get; set; }
        public bool? QnSectiondCap113 { get; set; }
        public bool? QnSectiondCap114 { get; set; }
        public bool? QnSectiondCap115 { get; set; }
        public string QnSectiondCap2 { get; set; }
        public bool? QnSectiondCap21 { get; set; }
        public bool? QnSectiondCap22 { get; set; }
        public bool? QnSectiondCap23 { get; set; }
        public bool? QnSectiondCap24 { get; set; }
        public bool? QnSectiondCap25 { get; set; }
        public bool? QnSectiondCap26 { get; set; }
        public bool? QnSectiondCap27 { get; set; }
        public bool? QnSectiondCap28 { get; set; }
        public bool? QnSectiondCap29 { get; set; }
        public bool? QnSectiondCap210 { get; set; }
        public bool? QnSectiondCap211 { get; set; }
        public bool? QnSectiondCap212 { get; set; }
        public bool? QnSectiondCap213 { get; set; }
        public bool? QnSectiondCap214 { get; set; }
        public bool? QnSectiondCap215 { get; set; }
        public string QnSectiondCap3Main { get; set; }
        public bool? QnSectiondCap31 { get; set; }
        public bool? QnSectiondCap32 { get; set; }
        public bool? QnSectiondCap33 { get; set; }
        public bool? QnSectiondCap34 { get; set; }
        public bool? QnSectiondCap35 { get; set; }
        public bool? QnSectiondCap36 { get; set; }
        public bool? QnSectiondCap37 { get; set; }
        public bool? QnSectiondCap38 { get; set; }
        public bool? QnSectiondCap39 { get; set; }
        public bool? QnSectiondCap310 { get; set; }
        public bool? QnSectiondCap311 { get; set; }
        public bool? QnSectiondCap312 { get; set; }
        public bool? QnSectiondCap313 { get; set; }
        public bool? QnSectiondCap314 { get; set; }
        public bool? QnSectiondCap315 { get; set; }
        public string QnSectiondCap4Main { get; set; }
        public bool? QnSectiondCap41 { get; set; }
        public bool? QnSectiondCap42 { get; set; }
        public bool? QnSectiondCap43 { get; set; }
        public bool? QnSectiondCap44 { get; set; }
        public bool? QnSectiondCap45 { get; set; }
        public bool? QnSectiondCap46 { get; set; }
        public bool? QnSectiondCap47 { get; set; }
        public bool? QnSectiondCap48 { get; set; }
        public bool? QnSectiondCap49 { get; set; }
        public bool? QnSectiondCap410 { get; set; }
        public bool? QnSectiondCap411 { get; set; }
        public bool? QnSectiondCap412 { get; set; }
        public bool? QnSectiondCap413 { get; set; }
        public bool? QnSectiondCap414 { get; set; }
        public bool? QnSectiondCap415 { get; set; }
        public string QnSectiondCap5Main { get; set; }
        public bool? QnSectiondCap51 { get; set; }
        public bool? QnSectiondCap52 { get; set; }
        public bool? QnSectiondCap53 { get; set; }
        public bool? QnSectiondCap54 { get; set; }
        public bool? QnSectiondCap55 { get; set; }
        public bool? QnSectiondCap56 { get; set; }
        public bool? QnSectiondCap57 { get; set; }
        public bool? QnSectiondCap58 { get; set; }
        public bool? QnSectiondCap59 { get; set; }
        public bool? QnSectiondCap510 { get; set; }
        public bool? QnSectiondCap511 { get; set; }
        public bool? QnSectiondCap512 { get; set; }
        public bool? QnSectiondCap513 { get; set; }
        public bool? QnSectiondCap514 { get; set; }
        public bool? QnSectiondCap515 { get; set; }
        public string QnSectiondCap6Main { get; set; }
        public bool? QnSectiondCap61 { get; set; }
        public bool? QnSectiondCap62 { get; set; }
        public bool? QnSectiondCap63 { get; set; }
        public bool? QnSectiondCap64 { get; set; }
        public bool? QnSectiondCap65 { get; set; }
        public bool? QnSectiondCap66 { get; set; }
        public bool? QnSectiondCap67 { get; set; }
        public bool? QnSectiondCap68 { get; set; }
        public bool? QnSectiondCap69 { get; set; }
        public bool? QnSectiondCap610 { get; set; }
        public bool? QnSectiondCap611 { get; set; }
        public bool? QnSectiondCap612 { get; set; }
        public bool? QnSectiondCap613 { get; set; }
        public bool? QnSectiondCap614 { get; set; }
        public bool? QnSectiondCap615 { get; set; }
        public string QnSectiondCap7Main { get; set; }
        public bool? QnSectiondCap71 { get; set; }
        public bool? QnSectiondCap72 { get; set; }
        public bool? QnSectiondCap73 { get; set; }
        public bool? QnSectiondCap74 { get; set; }
        public bool? QnSectiondCap75 { get; set; }
        public bool? QnSectiondCap76 { get; set; }
        public bool? QnSectiondCap77 { get; set; }
        public bool? QnSectiondCap78 { get; set; }
        public bool? QnSectiondCap79 { get; set; }
        public bool? QnSectiondCap710 { get; set; }
        public bool? QnSectiondCap711 { get; set; }
        public bool? QnSectiondCap712 { get; set; }
        public bool? QnSectiondCap713 { get; set; }
        public bool? QnSectiondCap714 { get; set; }
        public bool? QnSectiondCap715 { get; set; }
        public string QnSectiondCap8Main { get; set; }
        public bool? QnSectiondCap81 { get; set; }
        public bool? QnSectiondCap82 { get; set; }
        public bool? QnSectiondCap83 { get; set; }
        public bool? QnSectiondCap84 { get; set; }
        public bool? QnSectiondCap85 { get; set; }
        public bool? QnSectiondCap86 { get; set; }
        public bool? QnSectiondCap87 { get; set; }
        public bool? QnSectiondCap88 { get; set; }
        public bool? QnSectiondCap89 { get; set; }
        public bool? QnSectiondCap810 { get; set; }
        public bool? QnSectiondCap811 { get; set; }
        public bool? QnSectiondCap812 { get; set; }
        public bool? QnSectiondCap813 { get; set; }
        public bool? QnSectiondCap814 { get; set; }
        public bool? QnSectiondCap815 { get; set; }
        public string QnSectiondCap9Main { get; set; }
        public bool? QnSectiondCap91 { get; set; }
        public bool? QnSectiondCap92 { get; set; }
        public bool? QnSectiondCap93 { get; set; }
        public bool? QnSectiondCap94 { get; set; }
        public bool? QnSectiondCap95 { get; set; }
        public bool? QnSectiondCap96 { get; set; }
        public bool? QnSectiondCap97 { get; set; }
        public bool? QnSectiondCap98 { get; set; }
        public bool? QnSectiondCap99 { get; set; }
        public bool? QnSectiondCap910 { get; set; }
        public bool? QnSectiondCap911 { get; set; }
        public bool? QnSectiondCap912 { get; set; }
        public bool? QnSectiondCap913 { get; set; }
        public bool? QnSectiondCap914 { get; set; }
        public bool? QnSectiondCap915 { get; set; }
        public string QnSectiondCap10Main { get; set; }
        public bool? QnSectiondCap101 { get; set; }
        public bool? QnSectiondCap102 { get; set; }
        public bool? QnSectiondCap103 { get; set; }
        public bool? QnSectiondCap104 { get; set; }
        public bool? QnSectiondCap105 { get; set; }
        public bool? QnSectiondCap106 { get; set; }
        public bool? QnSectiondCap107 { get; set; }
        public bool? QnSectiondCap108 { get; set; }
        public bool? QnSectiondCap109 { get; set; }
        public bool? QnSectiondCap1010 { get; set; }
        public bool? QnSectiondCap1011 { get; set; }
        public bool? QnSectiondCap1012 { get; set; }
        public bool? QnSectiondCap1013 { get; set; }
        public bool? QnSectiondCap1014 { get; set; }
        public bool? QnSectiondCap1015 { get; set; }
        public string QnSectiondCap11Main { get; set; }
        public bool? QnSectiondCap1111 { get; set; }
        public bool? QnSectiondCap1121 { get; set; }
        public bool? QnSectiondCap1131 { get; set; }
        public bool? QnSectiondCap1141 { get; set; }
        public bool? QnSectiondCap1151 { get; set; }
        public bool? QnSectiondCap116 { get; set; }
        public bool? QnSectiondCap117 { get; set; }
        public bool? QnSectiondCap118 { get; set; }
        public bool? QnSectiondCap119 { get; set; }
        public bool? QnSectiondCap1110 { get; set; }
        public bool? QnSectiondCap11111 { get; set; }
        public bool? QnSectiondCap1112 { get; set; }
        public bool? QnSectiondCap1113 { get; set; }
        public bool? QnSectiondCap1114 { get; set; }
        public bool? QnSectiondCap1115 { get; set; }
        public string QnSectiondCap12Main { get; set; }
        public bool? QnSectiondCap121 { get; set; }
        public bool? QnSectiondCap122 { get; set; }
        public bool? QnSectiondCap123 { get; set; }
        public bool? QnSectiondCap124 { get; set; }
        public bool? QnSectiondCap125 { get; set; }
        public bool? QnSectiondCap126 { get; set; }
        public bool? QnSectiondCap127 { get; set; }
        public bool? QnSectiondCap128 { get; set; }
        public bool? QnSectiondCap129 { get; set; }
        public bool? QnSectiondCap1210 { get; set; }
        public bool? QnSectiondCap1211 { get; set; }
        public bool? QnSectiondCap1212 { get; set; }
        public bool? QnSectiondCap1213 { get; set; }
        public bool? QnSectiondCap1214 { get; set; }
        public bool? QnSectiondCap1215 { get; set; }
        public string QnSectiondCap13Main { get; set; }
        public bool? QnSectiondCap131 { get; set; }
        public bool? QnSectiondCap132 { get; set; }
        public bool? QnSectiondCap133 { get; set; }
        public bool? QnSectiondCap134 { get; set; }
        public bool? QnSectiondCap135 { get; set; }
        public bool? QnSectiondCap136 { get; set; }
        public bool? QnSectiondCap137 { get; set; }
        public bool? QnSectiondCap138 { get; set; }
        public bool? QnSectiondCap139 { get; set; }
        public bool? QnSectiondCap1310 { get; set; }
        public bool? QnSectiondCap1311 { get; set; }
        public bool? QnSectiondCap1312 { get; set; }
        public bool? QnSectiondCap1313 { get; set; }
        public bool? QnSectiondCap1314 { get; set; }
        public bool? QnSectiondCap1315 { get; set; }
        public string QnSectiondCap14Main { get; set; }
        public bool? QnSectiondCap141 { get; set; }
        public bool? QnSectiondCap142 { get; set; }
        public bool? QnSectiondCap143 { get; set; }
        public bool? QnSectiondCap144 { get; set; }
        public bool? QnSectiondCap145 { get; set; }
        public bool? QnSectiondCap146 { get; set; }
        public bool? QnSectiondCap147 { get; set; }
        public bool? QnSectiondCap148 { get; set; }
        public bool? QnSectiondCap149 { get; set; }
        public bool? QnSectiondCap1410 { get; set; }
        public bool? QnSectiondCap1411 { get; set; }
        public bool? QnSectiondCap1412 { get; set; }
        public bool? QnSectiondCap1413 { get; set; }
        public bool? QnSectiondCap1414 { get; set; }
        public bool? QnSectiondCap1415 { get; set; }
        public string QnSectiondCap15Main { get; set; }
        public bool? QnSectiondCap151 { get; set; }
        public bool? QnSectiondCap152 { get; set; }
        public bool? QnSectiondCap153 { get; set; }
        public bool? QnSectiondCap154 { get; set; }
        public bool? QnSectiondCap155 { get; set; }
        public bool? QnSectiondCap156 { get; set; }
        public bool? QnSectiondCap157 { get; set; }
        public bool? QnSectiondCap158 { get; set; }
        public bool? QnSectiondCap159 { get; set; }
        public bool? QnSectiondCap1510 { get; set; }
        public bool? QnSectiondCap1511 { get; set; }
        public bool? QnSectiondCap1512 { get; set; }
        public bool? QnSectiondCap1513 { get; set; }
        public bool? QnSectiondCap1514 { get; set; }
        public bool? QnSectiondCap1515 { get; set; }
        public string QnSectiondCap16Main { get; set; }
        public bool? QnSectiondCap161 { get; set; }
        public bool? QnSectiondCap162 { get; set; }
        public bool? QnSectiondCap163 { get; set; }
        public bool? QnSectiondCap164 { get; set; }
        public bool? QnSectiondCap165 { get; set; }
        public bool? QnSectiondCap166 { get; set; }
        public bool? QnSectiondCap167 { get; set; }
        public bool? QnSectiondCap168 { get; set; }
        public bool? QnSectiondCap169 { get; set; }
        public bool? QnSectiondCap1610 { get; set; }
        public bool? QnSectiondCap1611 { get; set; }
        public bool? QnSectiondCap1612 { get; set; }
        public bool? QnSectiondCap1613 { get; set; }
        public bool? QnSectiondCap1614 { get; set; }
        public bool? QnSectiondCap1615 { get; set; }
        public string QnSectiondCap17Main { get; set; }
        public bool? QnSectiondCap171 { get; set; }
        public bool? QnSectiondCap172 { get; set; }
        public bool? QnSectiondCap173 { get; set; }
        public bool? QnSectiondCap174 { get; set; }
        public bool? QnSectiondCap175 { get; set; }
        public bool? QnSectiondCap176 { get; set; }
        public bool? QnSectiondCap177 { get; set; }
        public bool? QnSectiondCap178 { get; set; }
        public bool? QnSectiondCap179 { get; set; }
        public bool? QnSectiondCap1710 { get; set; }
        public bool? QnSectiondCap1711 { get; set; }
        public bool? QnSectiondCap1712 { get; set; }
        public bool? QnSectiondCap1713 { get; set; }
        public bool? QnSectiondCap1714 { get; set; }
        public bool? QnSectiondCap1715 { get; set; }
        public string QnSectiondCap18Main { get; set; }
        public bool? QnSectiondCap181 { get; set; }
        public bool? QnSectiondCap182 { get; set; }
        public bool? QnSectiondCap183 { get; set; }
        public bool? QnSectiondCap184 { get; set; }
        public bool? QnSectiondCap185 { get; set; }
        public bool? QnSectiondCap186 { get; set; }
        public bool? QnSectiondCap187 { get; set; }
        public bool? QnSectiondCap188 { get; set; }
        public bool? QnSectiondCap189 { get; set; }
        public bool? QnSectiondCap1810 { get; set; }
        public bool? QnSectiondCap1811 { get; set; }
        public bool? QnSectiondCap1812 { get; set; }
        public bool? QnSectiondCap1813 { get; set; }
        public bool? QnSectiondCap1814 { get; set; }
        public bool? QnSectiondCap1815 { get; set; }
        public string QnSectioneNecpa { get; set; }
        public string QnSectioneNecpa1 { get; set; }
        public string QnSectioneNecpa2 { get; set; }
        public string QnSectioneNecpa3 { get; set; }
        public string QnSectioneNecpa4 { get; set; }
        public string QnSectioneNecpa5 { get; set; }
        public string QnSectioneNecpa6 { get; set; }
        public string QnSectioneNecpa7 { get; set; }
        public string QnSectioneNecpa8 { get; set; }
        public string QnSectioneNecpa9 { get; set; }
        public string QnSectioneNecpa10 { get; set; }
        public string QnSectioneNecpa11 { get; set; }
        public string QnSectioneNecpa12 { get; set; }
        public string QnSectioneNecpa13 { get; set; }
        public string QnSectioneNecpa14 { get; set; }
        public string QnSectioneNecpa15 { get; set; }
        public string QnSectioneNecpa16 { get; set; }
        public string QnSectioneNecpa17 { get; set; }
        public string QnSectioneNecpa18 { get; set; }
        public string QnSectioneNecpa19 { get; set; }
        public string QnSectioneNecpa20 { get; set; }
        public bool? QnSectioneNecpa21 { get; set; }
        public string QnSectioneOtherNecpa { get; set; }
        public string QnSectioneNecpa110 { get; set; }
        public string QnSectioneNecpa22 { get; set; }
        public string QnSectioneNecpa31 { get; set; }
        public string QnSectioneNecpa41 { get; set; }
        public string QnSectioneNecpa51 { get; set; }
        public string QnSectioneNecpa61 { get; set; }
        public string QnSectioneNecpa71 { get; set; }
        public string QnSectioneNecpa81 { get; set; }
        public string QnSectioneNecpa91 { get; set; }
        public string QnSectioneNecpa101 { get; set; }
        public string QnSectioneNecpa111 { get; set; }
        public string QnSectioneNecpa121 { get; set; }
        public string QnSectioneNecpa131 { get; set; }
        public string QnSectioneNecpa141 { get; set; }
        public string QnSectioneNecpa151 { get; set; }
        public string QnSectioneNecpa161 { get; set; }
        public string QnSectioneNecpa171 { get; set; }
        public string QnSectioneNecpa181 { get; set; }
        public string QnSectioneNecpa191 { get; set; }
        public string QnSectioneNecpa201 { get; set; }
        public string QnAckNoteM { get; set; }
        public DateTime? QnEnd { get; set; }
        public string QnZ4 { get; set; }
        public string QnZ4Latitude { get; set; }
        public string QnZ4Longitude { get; set; }
        public string QnZ4Precision { get; set; }
        public string QnComments { get; set; }
        public string QnAck2 { get; set; }
        public string QnSignature { get; set; }
        public string MetaInstanceId { get; set; }
        public string Uuid { get; set; }
        public DateTime? SubmissionTime { get; set; }
        public double? Index { get; set; }
        public string ParentTableName { get; set; }
        public double? ParentIndex { get; set; }
        public string Tags { get; set; }
        public string Notes { get; set; }
        public string Version { get; set; }
        public double? Duration { get; set; }
        public string SubmittedBy { get; set; }
        public double? XformId { get; set; }
        public DateTime? LastUpdatedAt { get; set; }
    }
}
