using System;
using System.Collections.Generic;

#nullable disable

namespace USAIDICANBLAZOR.Models
{
    public partial class OnatestRms1
    {
        public string District { get; set; }
        public string Subcounty { get; set; }
        public string Village { get; set; }
        public string LocationGroupid { get; set; }
        public string LocationGroupname { get; set; }
        public string Ra { get; set; }
        public string AZ6 { get; set; }
        public string AZ7 { get; set; }
        public string AZ8 { get; set; }
        public string QnQn11 { get; set; }
        public string QnQn121 { get; set; }
        public string QnQn13 { get; set; }
        public string QnQn14 { get; set; }
        public string QnQn15 { get; set; }
        public string QnOtherQn15 { get; set; }
        public string QnQn16 { get; set; }
        public string QnQn16Seasons { get; set; }
        public string QnSectioncQn21 { get; set; }
        public string QnSectioncQn22 { get; set; }
        public string QnSectioncQn221 { get; set; }
        public string QnSectioncQn23 { get; set; }
        public string QnSectioncQn231 { get; set; }
        public string QnSectioncQn232 { get; set; }
        public string QnSectioncQn233 { get; set; }
        public string QnSectioncQn234 { get; set; }
        public string QnSectioncQn235 { get; set; }
        public string QnSectioncQn236 { get; set; }
        public string QnSectioncQn237 { get; set; }
        public string QnSectioncQn238 { get; set; }
        public string QnSectioncQn239 { get; set; }
        public string QnSectioncOtherQn23 { get; set; }
        public string QnSectioncQn2311 { get; set; }
        public string QnSectioncQn23111 { get; set; }
        public string QnSectioncQn2312 { get; set; }
        public string QnSectioncQn2313 { get; set; }
        public string QnSectioncQn2314 { get; set; }
        public string QnSectioncQn2315 { get; set; }
        public string QnSectioncQn24 { get; set; }
        public string QnSectioncQn25 { get; set; }
        public string QnSectioncQn251 { get; set; }
        public string QnSectioncQn252 { get; set; }
        public string QnSectioncQn253 { get; set; }
        public string QnSectioncQn254 { get; set; }
        public string QnSectioncQn255 { get; set; }
        public string QnSectioncQn256 { get; set; }
        public string QnSectioncQn257 { get; set; }
        public string QnSectioncQn258 { get; set; }
        public string QnSectioncQn259 { get; set; }
        public string QnSectioncQn2511 { get; set; }
        public string QnSectioncQn25111 { get; set; }
        public string QnSectioncQn2512 { get; set; }
        public string QnSectioncQn2513 { get; set; }
        public string QnSectioncQn2514 { get; set; }
        public string QnSectioncQn2515 { get; set; }
        public string QnSectioncQn2516 { get; set; }
        public string QnSectioncQn2517 { get; set; }
        public string QnSectioncQn2518 { get; set; }
        public string QnSectioncQn2521 { get; set; }
        public string QnSectioncQn25211 { get; set; }
        public string QnSectioncQn2522 { get; set; }
        public string QnSectioncQn2523 { get; set; }
        public string QnSectioncQn2524 { get; set; }
        public string QnSectioncQn2525 { get; set; }
        public string QnSectioncQn2526 { get; set; }
        public string QnSectioncQn2527 { get; set; }
        public string QnSectioncQn2528 { get; set; }
        public string QnSectioncQn2531 { get; set; }
        public string QnSectioncQn25311 { get; set; }
        public string QnSectioncQn2532 { get; set; }
        public string QnSectioncQn2533 { get; set; }
        public string QnSectioncQn2534 { get; set; }
        public string QnSectioncQn2535 { get; set; }
        public string QnSectioncQn2536 { get; set; }
        public string QnSectioncQn2537 { get; set; }
        public string QnSectioncQn2538 { get; set; }
        public string QnSectioncQn2541 { get; set; }
        public string QnSectioncQn25411 { get; set; }
        public string QnSectioncQn2542 { get; set; }
        public string QnSectioncQn2543 { get; set; }
        public string QnSectioncQn2544 { get; set; }
        public string QnSectioncQn2545 { get; set; }
        public string QnSectioncQn2546 { get; set; }
        public string QnSectioncQn2547 { get; set; }
        public string QnSectioncQn2548 { get; set; }
        public string QnSectioncQn2551 { get; set; }
        public string QnSectioncQn25511 { get; set; }
        public string QnSectioncQn2552 { get; set; }
        public string QnSectioncQn2553 { get; set; }
        public string QnSectioncQn2554 { get; set; }
        public string QnSectioncQn2555 { get; set; }
        public string QnSectioncQn2556 { get; set; }
        public string QnSectioncQn2557 { get; set; }
        public string QnSectioncQn2558 { get; set; }
        public string QnSectioncQn2561 { get; set; }
        public string QnSectioncQn25611 { get; set; }
        public string QnSectioncQn2562 { get; set; }
        public string QnSectioncQn2563 { get; set; }
        public string QnSectioncQn2564 { get; set; }
        public string QnSectioncQn2565 { get; set; }
        public string QnSectioncQn2566 { get; set; }
        public string QnSectioncQn2567 { get; set; }
        public string QnSectioncQn2568 { get; set; }
        public string QnSectioncQn2571 { get; set; }
        public string QnSectioncQn25711 { get; set; }
        public string QnSectioncQn2572 { get; set; }
        public string QnSectioncQn2573 { get; set; }
        public string QnSectioncQn2574 { get; set; }
        public string QnSectioncQn2575 { get; set; }
        public string QnSectioncQn2576 { get; set; }
        public string QnSectioncQn2577 { get; set; }
        public string QnSectioncQn2578 { get; set; }
        public string QnSectioncQn2581 { get; set; }
        public string QnSectioncQn25811 { get; set; }
        public string QnSectioncQn2582 { get; set; }
        public string QnSectioncQn2583 { get; set; }
        public string QnSectioncQn2584 { get; set; }
        public string QnSectioncQn2585 { get; set; }
        public string QnSectioncQn2586 { get; set; }
        public string QnSectioncQn2587 { get; set; }
        public string QnSectioncQn2588 { get; set; }
        public string QnSectioncQn2591 { get; set; }
        public string QnSectioncQn25911 { get; set; }
        public string QnSectioncQn2592 { get; set; }
        public string QnSectioncQn2593 { get; set; }
        public string QnSectioncQn2594 { get; set; }
        public string QnSectioncQn2595 { get; set; }
        public string QnSectioncQn2596 { get; set; }
        public string QnSectioncQn2597 { get; set; }
        public string QnSectioncQn2598 { get; set; }
        public string QnSectioncQn27 { get; set; }
        public string QnSectioncQn28 { get; set; }
        public string QnSectioncQn29 { get; set; }
        public string QnSectioncQn291 { get; set; }
        public string QnSectioncQn292 { get; set; }
        public string QnSectioncQn293 { get; set; }
        public string QnSectioncQn294 { get; set; }
        public string QnSectioncQn295 { get; set; }
        public string QnSectioncQn296 { get; set; }
        public string QnSectioncQn297 { get; set; }
        public string QnSectioncQn298 { get; set; }
        public string QnSectioncQn299 { get; set; }
        public string QnSectioncQn210 { get; set; }
        public string QnSectioncQn211 { get; set; }
        public string QnSectioncQn212 { get; set; }
        public string QnSectioncQn213 { get; set; }
        public string QnSectioncQn2131 { get; set; }
        public string QnSectioncQn21311 { get; set; }
        public string QnSectioncQn21312 { get; set; }
        public string QnSectioncQn21313 { get; set; }
        public string QnSectioncQn21314 { get; set; }
        public string QnSectioncQn21315 { get; set; }
        public string QnSectioncQn216 { get; set; }
        public string QnSectiondShocks { get; set; }
        public string QnSectiondShocks1 { get; set; }
        public string QnSectiondShocks2 { get; set; }
        public string QnSectiondShocks3 { get; set; }
        public string QnSectiondShocks4 { get; set; }
        public string QnSectiondShocks5 { get; set; }
        public string QnSectiondShocks6 { get; set; }
        public string QnSectiondShocks7 { get; set; }
        public string QnSectiondShocks8 { get; set; }
        public string QnSectiondShocks9 { get; set; }
        public string QnSectiondShocks10 { get; set; }
        public string QnSectiondShocks11 { get; set; }
        public string QnSectiondShocks12 { get; set; }
        public string QnSectiondShocks13 { get; set; }
        public string QnSectiondShocks14 { get; set; }
        public string QnSectiondShocks15 { get; set; }
        public string QnSectiondShocks16 { get; set; }
        public string QnSectiondShocks17 { get; set; }
        public string QnSectiondShocks18 { get; set; }
        public string QnSectiondShocks19 { get; set; }
        public string QnSectiondShocks20 { get; set; }
        public string QnSectiondShocks110 { get; set; }
        public string QnSectiondShocks21 { get; set; }
        public string QnSectiondShocks31 { get; set; }
        public string QnSectiondShocks41 { get; set; }
        public string QnSectiondShocks51 { get; set; }
        public string QnSectiondShocks61 { get; set; }
        public string QnSectiondShocks71 { get; set; }
        public string QnSectiondShocks81 { get; set; }
        public string QnSectiondShocks91 { get; set; }
        public string QnSectiondShocks101 { get; set; }
        public string QnSectiondShocks111 { get; set; }
        public string QnSectiondShocks121 { get; set; }
        public string QnSectiondShocks131 { get; set; }
        public string QnSectiondShocks141 { get; set; }
        public string QnSectiondShocks151 { get; set; }
        public string QnSectiondShocks161 { get; set; }
        public string QnSectiondShocks171 { get; set; }
        public string QnSectiondShocks181 { get; set; }
        public string QnSectiondShocks191 { get; set; }
        public string QnSectiondCap1 { get; set; }
        public string QnSectiondCap11 { get; set; }
        public string QnSectiondCap12 { get; set; }
        public string QnSectiondCap13 { get; set; }
        public string QnSectiondCap14 { get; set; }
        public string QnSectiondCap15 { get; set; }
        public string QnSectiondCap16 { get; set; }
        public string QnSectiondCap17 { get; set; }
        public string QnSectiondCap18 { get; set; }
        public string QnSectiondCap19 { get; set; }
        public string QnSectiondCap110 { get; set; }
        public string QnSectiondCap111 { get; set; }
        public string QnSectiondCap112 { get; set; }
        public string QnSectiondCap113 { get; set; }
        public string QnSectiondCap114 { get; set; }
        public string QnSectiondCap2 { get; set; }
        public string QnSectiondCap21 { get; set; }
        public string QnSectiondCap22 { get; set; }
        public string QnSectiondCap23 { get; set; }
        public string QnSectiondCap24 { get; set; }
        public string QnSectiondCap25 { get; set; }
        public string QnSectiondCap26 { get; set; }
        public string QnSectiondCap27 { get; set; }
        public string QnSectiondCap28 { get; set; }
        public string QnSectiondCap29 { get; set; }
        public string QnSectiondCap210 { get; set; }
        public string QnSectiondCap211 { get; set; }
        public string QnSectiondCap212 { get; set; }
        public string QnSectiondCap213 { get; set; }
        public string QnSectiondCap214 { get; set; }
        public string QnSectiondCap3 { get; set; }
        public string QnSectiondCap31 { get; set; }
        public string QnSectiondCap32 { get; set; }
        public string QnSectiondCap33 { get; set; }
        public string QnSectiondCap34 { get; set; }
        public string QnSectiondCap35 { get; set; }
        public string QnSectiondCap36 { get; set; }
        public string QnSectiondCap37 { get; set; }
        public string QnSectiondCap38 { get; set; }
        public string QnSectiondCap39 { get; set; }
        public string QnSectiondCap310 { get; set; }
        public string QnSectiondCap311 { get; set; }
        public string QnSectiondCap312 { get; set; }
        public string QnSectiondCap313 { get; set; }
        public string QnSectiondCap314 { get; set; }
        public string QnSectiondCap4 { get; set; }
        public string QnSectiondCap41 { get; set; }
        public string QnSectiondCap42 { get; set; }
        public string QnSectiondCap43 { get; set; }
        public string QnSectiondCap44 { get; set; }
        public string QnSectiondCap45 { get; set; }
        public string QnSectiondCap46 { get; set; }
        public string QnSectiondCap47 { get; set; }
        public string QnSectiondCap48 { get; set; }
        public string QnSectiondCap49 { get; set; }
        public string QnSectiondCap410 { get; set; }
        public string QnSectiondCap411 { get; set; }
        public string QnSectiondCap412 { get; set; }
        public string QnSectiondCap413 { get; set; }
        public string QnSectiondCap414 { get; set; }
        public string QnSectiondCap5 { get; set; }
        public string QnSectiondCap51 { get; set; }
        public string QnSectiondCap52 { get; set; }
    }
}
