using System;
using System.Collections.Generic;

#nullable disable

namespace USAIDICANBLAZOR.Models
{
    public partial class OnatestIbs2020Gamma
    {
        public string District { get; set; }
        public string Subcounty { get; set; }
        public string Village { get; set; }
        public string LocationGroupid { get; set; }
        public string LocationGroupname { get; set; }
        public string Ra { get; set; }
        public string AZ6 { get; set; }
        public string AZ7 { get; set; }
        public string AZ8 { get; set; }
        public string QnStart { get; set; }
        public string QnBSexres { get; set; }
        public double? QnBAge { get; set; }
        public string QnCCNote { get; set; }
        public string QnCC1 { get; set; }
        public string QnCC2 { get; set; }
        public double? QnCC3 { get; set; }
        public string QnCC4 { get; set; }
        public string QnCC4Other { get; set; }
        public string QnCC5 { get; set; }
        public string QnCC6 { get; set; }
        public string QnCC6Other { get; set; }
        public double? QnProfileC7 { get; set; }
        public double? QnProfileC8 { get; set; }
        public double? QnProfileC9 { get; set; }
        public double? QnProfileC10 { get; set; }
        public double? QnProfileC11 { get; set; }
        public string QnProfileLesspri { get; set; }
        public double? QnProfileC12 { get; set; }
        public string QnProfileC15 { get; set; }
        public bool QnProfileC151 { get; set; }
        public bool QnProfileC152 { get; set; }
        public bool QnProfileC153 { get; set; }
        public bool QnProfileC154 { get; set; }
        public bool QnProfileC155 { get; set; }
        public bool QnProfileC156 { get; set; }
        public double? QnProfileC15x { get; set; }
        public string QnProfileC15x1 { get; set; }
        public bool QnProfileC15x11 { get; set; }
        public bool QnProfileC15x12 { get; set; }
        public bool QnProfileC15x13 { get; set; }
        public bool QnProfileC15x14 { get; set; }
        public bool QnProfileC15x15 { get; set; }
        public bool QnProfileC15x16 { get; set; }
        public bool QnProfileC15x17 { get; set; }
        public bool QnProfileC15x18 { get; set; }
        public bool QnProfileC15x19 { get; set; }
        public bool QnProfileC15x110 { get; set; }
        public bool QnProfileC15x111 { get; set; }
        public bool QnProfileC15x112 { get; set; }
        public bool QnProfileC15x113 { get; set; }
        public bool QnProfileC15x114 { get; set; }
        public bool QnProfileC15x115 { get; set; }
        public bool QnProfileC15x116 { get; set; }
        public double? QnProfileC15a { get; set; }
        public string QnProfileC15a1 { get; set; }
        public bool QnProfileC15a11 { get; set; }
        public bool QnProfileC15a12 { get; set; }
        public bool QnProfileC15a13 { get; set; }
        public bool QnProfileC15a14 { get; set; }
        public bool QnProfileC15a15 { get; set; }
        public bool QnProfileC15a16 { get; set; }
        public bool QnProfileC15a17 { get; set; }
        public bool QnProfileC15a18 { get; set; }
        public bool QnProfileC15a19 { get; set; }
        public bool QnProfileC15a110 { get; set; }
        public bool QnProfileC15a111 { get; set; }
        public bool QnProfileC15a112 { get; set; }
        public bool QnProfileC15a113 { get; set; }
        public bool QnProfileC15a114 { get; set; }
        public bool QnProfileC15a115 { get; set; }
        public bool QnProfileC15a116 { get; set; }
        public string QnProfileC15b { get; set; }
        public string QnProfileC15b1 { get; set; }
        public string QnProfileC15b11 { get; set; }
        public string QnProfileC15b12 { get; set; }
        public string QnProfileC15b13 { get; set; }
        public string QnProfileC15b14 { get; set; }
        public string QnProfileC15b15 { get; set; }
        public string QnProfileC15b16 { get; set; }
        public string QnProfileC15b17 { get; set; }
        public string QnProfileC15b18 { get; set; }
        public string QnProfileC15b19 { get; set; }
        public string QnProfileC15b110 { get; set; }
        public string QnProfileC15b111 { get; set; }
        public string QnProfileC15b112 { get; set; }
        public string QnProfileC15b113 { get; set; }
        public string QnProfileC15b114 { get; set; }
        public string QnProfileC15b115 { get; set; }
        public string QnProfileC15b116 { get; set; }
        public double? QnProfileC15c { get; set; }
        public string QnProfileC15c1 { get; set; }
        public bool QnProfileC15c11 { get; set; }
        public bool QnProfileC15c12 { get; set; }
        public bool QnProfileC15c13 { get; set; }
        public bool QnProfileC15c14 { get; set; }
        public bool QnProfileC15c15 { get; set; }
        public bool QnProfileC15c16 { get; set; }
        public bool QnProfileC15c17 { get; set; }
        public bool QnProfileC15c18 { get; set; }
        public bool QnProfileC15c19 { get; set; }
        public bool QnProfileC15c110 { get; set; }
        public bool QnProfileC15c111 { get; set; }
        public bool QnProfileC15c112 { get; set; }
        public bool QnProfileC15c113 { get; set; }
        public bool QnProfileC15c114 { get; set; }
        public bool QnProfileC15c115 { get; set; }
        public bool QnProfileC15c116 { get; set; }
        public double? QnProfileC15e { get; set; }
        public string QnProfileC15e1 { get; set; }
        public bool QnProfileC15e11 { get; set; }
        public bool QnProfileC15e12 { get; set; }
        public bool QnProfileC15e13 { get; set; }
        public bool QnProfileC15e14 { get; set; }
        public bool QnProfileC15e15 { get; set; }
        public bool QnProfileC15e16 { get; set; }
        public bool QnProfileC15e17 { get; set; }
        public bool QnProfileC15e18 { get; set; }
        public bool QnProfileC15e19 { get; set; }
        public bool QnProfileC15e110 { get; set; }
        public bool QnProfileC15e111 { get; set; }
        public bool QnProfileC15e112 { get; set; }
        public bool QnProfileC15e113 { get; set; }
        public bool QnProfileC15e114 { get; set; }
        public bool QnProfileC15e115 { get; set; }
        public bool QnProfileC15e116 { get; set; }
        public string QnProfileC16 { get; set; }
        public bool QnProfileC161 { get; set; }
        public bool QnProfileC162 { get; set; }
        public bool QnProfileC163 { get; set; }
        public bool QnProfileC164 { get; set; }
        public bool QnProfileC165 { get; set; }
        public bool QnProfileC166 { get; set; }
        public bool QnProfileC167 { get; set; }
        public bool QnProfileC168 { get; set; }
        public bool QnProfileC169 { get; set; }
        public bool QnProfileC1610 { get; set; }
        public bool QnProfileC1611 { get; set; }
        public bool QnProfileC1612 { get; set; }
        public bool QnProfileC1613 { get; set; }
        public bool QnProfileC1614 { get; set; }
        public bool QnProfileC1615 { get; set; }
        public bool QnProfileC1616 { get; set; }
        public string QnProfileOtherc16 { get; set; }
        public string QnProfileC13 { get; set; }
        public string QnProfileC14 { get; set; }
        public string QnFFIntro { get; set; }
        public string QnFF1 { get; set; }
        public double? QnFF1a { get; set; }
        public double? QnFF2 { get; set; }
        public string QnFF3 { get; set; }
        public double? QnFF5 { get; set; }
        public string QnFF6 { get; set; }
        public string QnFF7 { get; set; }
        public bool QnFF71 { get; set; }
        public bool QnFF72 { get; set; }
        public bool QnFF73 { get; set; }
        public bool QnFF729 { get; set; }
        public bool QnFF74 { get; set; }
        public bool QnFF75 { get; set; }
        public bool QnFF76 { get; set; }
        public bool QnFF77 { get; set; }
        public bool QnFF78 { get; set; }
        public bool QnFF79 { get; set; }
        public bool QnFF710 { get; set; }
        public bool QnFF711 { get; set; }
        public bool QnFF712 { get; set; }
        public bool QnFF713 { get; set; }
        public bool QnFF714 { get; set; }
        public bool QnFF715 { get; set; }
        public bool QnFF716 { get; set; }
        public bool QnFF717 { get; set; }
        public bool QnFF718 { get; set; }
        public bool QnFF719 { get; set; }
        public bool QnFF720 { get; set; }
        public bool QnFF721 { get; set; }
        public bool QnFF722 { get; set; }
        public bool QnFF723 { get; set; }
        public bool QnFF724 { get; set; }
        public bool QnFF725 { get; set; }
        public bool QnFF726 { get; set; }
        public bool QnFF727 { get; set; }
        public bool QnFF728 { get; set; }
        public string QnFCrp1 { get; set; }
        public string QnFCrp2 { get; set; }
        public string QnFCrp3 { get; set; }
        public string QnFCrp4 { get; set; }
        public string QnFCrp5 { get; set; }
        public string QnFCrp6 { get; set; }
        public string QnFCrp7 { get; set; }
        public string QnFCrp8 { get; set; }
        public string QnFCrp9 { get; set; }
        public string QnFCrp10 { get; set; }
        public string QnFCrp11 { get; set; }
        public string QnFCrp12 { get; set; }
        public string QnFCrp13 { get; set; }
        public string QnFCrp14 { get; set; }
        public string QnFCrp15 { get; set; }
        public string QnFCrp16 { get; set; }
        public string QnFCrp17 { get; set; }
        public string QnFCrp18 { get; set; }
        public string QnFCrp19 { get; set; }
        public string QnFCrp20 { get; set; }
        public string QnFCrp21 { get; set; }
        public string QnFCrp22 { get; set; }
        public string QnFCrp23 { get; set; }
        public string QnFCrp24 { get; set; }
        public string QnFCrp25 { get; set; }
        public string QnFCrp26 { get; set; }
        public string QnFCrp29 { get; set; }
        public string QnFF7trees { get; set; }
        public double? QnFNumTrees { get; set; }
        public string QnFF8 { get; set; }
        public bool QnFF81 { get; set; }
        public bool QnFF82 { get; set; }
        public bool QnFF83 { get; set; }
        public bool QnFF84 { get; set; }
        public bool QnFF85 { get; set; }
        public bool QnFF86 { get; set; }
        public bool QnFF87 { get; set; }
        public bool QnFF88 { get; set; }
        public bool QnFF89 { get; set; }
        public string QnFF9 { get; set; }
        public string QnFF10 { get; set; }
        public string QnFF11 { get; set; }
        public string QnFF12 { get; set; }
        public string QnFF13 { get; set; }
        public string QnFF14 { get; set; }
        public string QnFF15 { get; set; }
        public bool QnFF151 { get; set; }
        public bool QnFF152 { get; set; }
        public bool QnFF153 { get; set; }
        public bool QnFF154 { get; set; }
        public bool QnFF155 { get; set; }
        public bool QnFF156 { get; set; }
        public bool QnFF157 { get; set; }
        public bool QnFF158 { get; set; }
        public bool QnFF159 { get; set; }
        public bool QnFF1510 { get; set; }
        public string QnFF15Animal1 { get; set; }
        public string QnFF15Other1 { get; set; }
        public string QnFF15a1 { get; set; }
        public string QnFF15b1 { get; set; }
        public string QnFF15c1 { get; set; }
        public string QnFF15d1 { get; set; }
        public string QnFF15e1 { get; set; }
        public string QnFF15f1 { get; set; }
        public string QnFF15g1 { get; set; }
        public string QnFF15h1 { get; set; }
        public string QnFF15i1 { get; set; }
        public double? QnFF15a2 { get; set; }
        public double? QnFF15b2 { get; set; }
        public double? QnFF15c2 { get; set; }
        public double? QnFF15d2 { get; set; }
        public double? QnFF15e2 { get; set; }
        public double? QnFF15f2 { get; set; }
    }
}
