using System;
using System.Collections.Generic;

#nullable disable

namespace USAIDICANBLAZOR.Models
{
    public partial class ViewHhprofile
    {
        public double Id { get; set; }
        public string RespondentSexres { get; set; }
        public string GenderName { get; set; }
        public string RespondentMsres { get; set; }
        public string MaritalStatusName { get; set; }
        public string RespondentEducres { get; set; }
        public string EducationLevelName { get; set; }
        public string RespondentQ118 { get; set; }
        public string RespondentQ118Name { get; set; }
        public string RespondentQ119 { get; set; }
        public string RespondentQ119Name { get; set; }
        public string RespondentHivstatusRes { get; set; }
        public string RespondentHivstatusResName { get; set; }
        public string RespondentQ120 { get; set; }
        public string RespondentQ120Name { get; set; }
        public string HhHead { get; set; }
        public string HhHeadName { get; set; }
        public string HeadSx { get; set; }
        public string HeadSxName { get; set; }
        public string Rela { get; set; }
        public string RelativeName { get; set; }
        public string HeadMs { get; set; }
        public string HhheadMaritalStatusName { get; set; }
        public string HeadEduc { get; set; }
        public string HhheadHighestEducLevelName { get; set; }
        public string HeadQ127 { get; set; }
        public string HeadQ127Name { get; set; }
        public string Expr1 { get; set; }
        public string Description { get; set; }
        public string Expr2 { get; set; }
        public string HeadQ128 { get; set; }
        public string HeadQ128Name { get; set; }
        public string HeadHivstatusHh { get; set; }
        public string HeadHivstatusHhName { get; set; }
        public string HeadQ129 { get; set; }
        public string HeadQ129Name { get; set; }
        public string SrcIncome { get; set; }
        public bool SrcIncome1 { get; set; }
        public string SrcIncome1name { get; set; }
        public bool SrcIncome2 { get; set; }
        public string SrcIncome2name { get; set; }
        public bool SrcIncome3 { get; set; }
        public string SrcIncome3name { get; set; }
        public bool SrcIncome4 { get; set; }
        public string SrcIncome4name { get; set; }
        public bool SrcIncome5 { get; set; }
        public string SrcIncome5name { get; set; }
        public bool SrcIncome6 { get; set; }
        public string SrcIncome6name { get; set; }
        public bool SrcIncome7 { get; set; }
        public string SrcIncome7name { get; set; }
        public bool SrcIncome8 { get; set; }
        public string SrcIncome8name { get; set; }
        public bool SrcIncome9 { get; set; }
        public string SrcIncome9name { get; set; }
        public bool SrcIncome10 { get; set; }
        public string SrcIncome10name { get; set; }
        public bool SrcIncome11 { get; set; }
        public string SrcIncome11name { get; set; }
        public bool SrcIncome12 { get; set; }
        public string SrcIncome12name { get; set; }
        public bool SrcIncome13 { get; set; }
        public string SrcIncome13name { get; set; }
        public bool SrcIncome14 { get; set; }
        public string SrcIncome14name { get; set; }
        public bool SrcIncome15 { get; set; }
        public string SrcIncome15name { get; set; }
        public bool SrcIncome16 { get; set; }
        public string SrcIncome16name { get; set; }
        public string Exp { get; set; }
        public bool Exp1 { get; set; }
        public string Exp1name { get; set; }
        public bool Exp2 { get; set; }
        public string Exp2name { get; set; }
        public bool Exp3 { get; set; }
        public string Exp3name { get; set; }
        public bool Exp4 { get; set; }
        public string Exp4name { get; set; }
        public bool Exp5 { get; set; }
        public string Exp5name { get; set; }
        public bool Exp6 { get; set; }
        public string Exp6name { get; set; }
        public bool Exp7 { get; set; }
        public string Exp7name { get; set; }
        public bool Exp8 { get; set; }
        public string Exp8name { get; set; }
        public bool Exp9 { get; set; }
        public string Exp9name { get; set; }
        public bool Exp10 { get; set; }
        public string Exp10name { get; set; }
        public string LivestockAgent { get; set; }
        public string LivestockAgentName { get; set; }
        public string LivestockAssets { get; set; }
        public string Agri { get; set; }
        public string AgriName { get; set; }
        public string AgiAginputs { get; set; }
        public string Srcfood { get; set; }
        public string SrcofFoodName { get; set; }
        public string Foodgrp { get; set; }
        public string HhsHhs2 { get; set; }
        public string HhsHhs2Name { get; set; }
        public string HhsHhs2a { get; set; }
        public string HhsHhs2aName { get; set; }
        public string HhsHhs3 { get; set; }
        public string HhsHhs3Name { get; set; }
        public string HhsHhs3a { get; set; }
        public string HhsHhs3aName { get; set; }
        public string HhsHhs4 { get; set; }
        public string HhsHhs4Name { get; set; }
        public string HhsHhs4a { get; set; }
        public string HhsHhs4aName { get; set; }
        public string HhsHhs5 { get; set; }
        public string HhsHhs5Name { get; set; }
        public string HhsHhs5a { get; set; }
        public string HhsHhs5aName { get; set; }
        public string HhsHhs6 { get; set; }
        public string HhsHhs6Name { get; set; }
        public string HhsHhs6a { get; set; }
        public string HhsHhs6aName { get; set; }
        public string HhsHhs7 { get; set; }
        public string HhsHhs7Name { get; set; }
        public string HhsHhs7a { get; set; }
        public string HhsHhs7aName { get; set; }
        public string HhsHhs8 { get; set; }
        public string HhsHhs8Name { get; set; }
        public string HhsHhs8a { get; set; }
        public string HhsHhs8aName { get; set; }
        public string HhsHhs9 { get; set; }
        public string HhsHhs9Name { get; set; }
        public string HhsHhs9a { get; set; }
        public string HhsHhs9aName { get; set; }
        public string HhDecisionDecision1 { get; set; }
        public string HhDecisionDecision1Name { get; set; }
        public string HhDecisionDecision2 { get; set; }
        public string HhDecisionDecision2Name { get; set; }
        public string HhDecisionDecision3 { get; set; }
        public string HhDecisionDecision3Name { get; set; }
        public string HhDecisionDecision4 { get; set; }
        public string HhDecisionDecision4Name { get; set; }
        public string HhDecisionDecision5 { get; set; }
        public string HhDecisionDecision5Name { get; set; }
        public string HhDecisionDecision6 { get; set; }
        public string HhDecisionDecision6Name { get; set; }
        public string GvtGovt { get; set; }
        public string Fac { get; set; }
        public int? Usee { get; set; }
        public string UseeName { get; set; }
        public int? Use1 { get; set; }
        public string Use1Name { get; set; }
        public string Fieldteam { get; set; }
        public string Start { get; set; }
        public string Endd { get; set; }
        public string Deviceid { get; set; }
        public DateTime? PrDate { get; set; }
        public string LocRegion { get; set; }
        public string LocDistrict { get; set; }
        public string LocSubcounty { get; set; }
        public string LocParish { get; set; }
        public string Loc { get; set; }
        public string Gpid { get; set; }
        public string Ereid { get; set; }
        public string RespondentFname { get; set; }
        public string RespondentLname { get; set; }
        public string RespondentHh1 { get; set; }
        public string RespondentHh2 { get; set; }
        public string RespondentHhid { get; set; }
        public double? RespondentHhnum { get; set; }
        public double? RespondentAgeres { get; set; }
        public double? RespondentPhoneres { get; set; }
        public string OtherRela { get; set; }
        public string HeadFn { get; set; }
        public string HeadLn { get; set; }
        public double? HeadAgehh { get; set; }
        public double? HeadMob { get; set; }
        public string EconReservedNameForFieldListLabels48 { get; set; }
        public string EconSrcIncome1 { get; set; }
        public string EconSrcIncome2 { get; set; }
        public string EconSrcIncome3 { get; set; }
        public string EconSrcIncome4 { get; set; }
        public string EconSrcIncome5 { get; set; }
        public string EconSrcIncome6 { get; set; }
        public string EconSrcIncome7 { get; set; }
        public string EconSrcIncome8 { get; set; }
        public string EconSrcIncome9 { get; set; }
        public string EconSrcIncome10 { get; set; }
        public string EconSrcIncome11 { get; set; }
        public string EconSrcIncome12 { get; set; }
        public string EconSrcIncome13 { get; set; }
        public string EconSrcIncome14 { get; set; }
        public string EconSrcIncome15 { get; set; }
        public string EconSrcIncome16 { get; set; }
        public string ExpenditureReservedNameForFieldListLabels67 { get; set; }
        public string ExpenditureExp1 { get; set; }
        public string ExpenditureExp2 { get; set; }
        public string ExpenditureExp3 { get; set; }
        public string ExpenditureExp4 { get; set; }
        public string ExpenditureExp5 { get; set; }
        public string ExpenditureExp6 { get; set; }
        public string ExpenditureExp7 { get; set; }
        public string ExpenditureExp8 { get; set; }
        public string ExpenditureExp9 { get; set; }
        public string ExpenditureExp10 { get; set; }
        public string ExpenditureExp11 { get; set; }
        public bool LivestockAssets1 { get; set; }
        public bool LivestockAssets2 { get; set; }
        public bool LivestockAssets3 { get; set; }
        public bool LivestockAssets4 { get; set; }
        public bool LivestockAssets5 { get; set; }
        public bool LivestockAssets6 { get; set; }
        public bool LivestockAssets7 { get; set; }
        public bool LivestockAssets8 { get; set; }
        public bool LivestockAssets9 { get; set; }
        public bool LivestockAssets10 { get; set; }
        public bool LivestockAssets11 { get; set; }
        public bool LivestockAssets12 { get; set; }
        public bool LivestockAssets13 { get; set; }
        public bool LivestockAssets14 { get; set; }
        public string LivestockAssetOther { get; set; }
        public double? LivestockCattle { get; set; }
        public double? LivestockOxen { get; set; }
        public double? LivestockGoats { get; set; }
        public string LivestockSheep { get; set; }
        public string LivestockPigs { get; set; }
        public string LivestockDonkeys { get; set; }
        public string LivestockRabbits { get; set; }
        public double? LivestockChicken { get; set; }
        public string LivestockTurkey { get; set; }
        public string LivestockDucks { get; set; }
        public string LivestockFish { get; set; }
        public string LivestockBeehive { get; set; }
        public string LivestockOther { get; set; }
        public string ProdAssetsProd { get; set; }
        public bool ProdAssetsProd1 { get; set; }
        public bool ProdAssetsProd2 { get; set; }
        public bool ProdAssetsProd3 { get; set; }
        public bool ProdAssetsProd4 { get; set; }
        public bool ProdAssetsProd5 { get; set; }
        public bool ProdAssetsProd6 { get; set; }
        public bool ProdAssetsProd7 { get; set; }
        public bool ProdAssetsProd8 { get; set; }
        public bool ProdAssetsProd9 { get; set; }
        public bool ProdAssetsProd10 { get; set; }
        public bool ProdAssetsProd11 { get; set; }
        public bool ProdAssetsProd12 { get; set; }
        public bool ProdAssetsProd13 { get; set; }
        public bool ProdAssetsProd14 { get; set; }
        public bool ProdAssetsProd15 { get; set; }
        public bool ProdAssetsProd16 { get; set; }
        public bool ProdAssetsProd17 { get; set; }
        public bool ProdAssetsProd18 { get; set; }
        public bool ProdAssetsProd19 { get; set; }
        public bool ProdAssetsProd20 { get; set; }
        public double? ProdAssetsProd110 { get; set; }
        public string ProdAssetsProd21 { get; set; }
        public string ProdAssetsProd31 { get; set; }
        public double? ProdAssetsProd41 { get; set; }
        public double? ProdAssetsProd51 { get; set; }
        public double? ProdAssetsProd61 { get; set; }
        public double? ProdAssetsProd71 { get; set; }
        public string ProdAssetsProd81 { get; set; }
        public double? ProdAssetsProd91 { get; set; }
        public string ProdAssetsProd101 { get; set; }
        public string ProdAssetsProd111 { get; set; }
        public string ProdAssetsProd121 { get; set; }
        public string ProdAssetsProd131 { get; set; }
        public string ProdAssetsProd141 { get; set; }
        public string ProdAssetsProd151 { get; set; }
        public string ProdAssetsProd161 { get; set; }
        public string ProdAssetsProd171 { get; set; }
        public string ProdAssetsProd181 { get; set; }
        public double? ProdAssetsProd191 { get; set; }
        public bool AgiAginputs1 { get; set; }
        public bool AgiAginputs2 { get; set; }
        public bool AgiAginputs3 { get; set; }
        public bool AgiAginputs4 { get; set; }
        public bool AgiAginputs5 { get; set; }
        public bool AgiAginputs6 { get; set; }
        public bool AgiAginputs7 { get; set; }
        public bool AgiAginputs8 { get; set; }
        public bool AgiAginputs9 { get; set; }
        public bool AgiAginputs10 { get; set; }
        public bool AgiAginputs11 { get; set; }
        public bool AgiAginputs12 { get; set; }
        public bool AgiAginputs13 { get; set; }
        public bool AgiAginputs14 { get; set; }
        public string AgiAgr1 { get; set; }
        public string AgiAgr2 { get; set; }
        public string AgiAgr3 { get; set; }
        public string AgiAgr4 { get; set; }
        public string AgiAgr5 { get; set; }
        public double? AgiAgr6 { get; set; }
        public string AgiAgr7 { get; set; }
        public string AgiAgr8 { get; set; }
        public string AgiAgr9 { get; set; }
        public double? AgiAgr10 { get; set; }
        public string AgiAgr11 { get; set; }
        public string AgiAgr12 { get; set; }
        public double? AgiAgr13 { get; set; }
        public double? Meals { get; set; }
        public bool Foodgrp1 { get; set; }
        public bool Foodgrp2 { get; set; }
        public bool Foodgrp3 { get; set; }
        public bool Foodgrp4 { get; set; }
        public bool Foodgrp5 { get; set; }
        public bool Foodgrp6 { get; set; }
        public bool Foodgrp7 { get; set; }
        public double? Fd1 { get; set; }
        public double? Fd2 { get; set; }
        public string Fd3 { get; set; }
        public double? Fd4 { get; set; }
        public string Fd5 { get; set; }
        public double? Fd6 { get; set; }
        public double? Fd7 { get; set; }
        public string HhsHhs1 { get; set; }
        public string HhsHhs1a { get; set; }
        public string HhDecisionOtherDcs1 { get; set; }
        public string HhDecisionOtherDcs2 { get; set; }
        public string HhDecisionOtherDcs3 { get; set; }
        public string HhDecisionOtherDcs5 { get; set; }
        public string HhDecisionOtherDcs4 { get; set; }
        public string HhDecisionOtherDc6 { get; set; }
        public bool GvtGovt1 { get; set; }
        public bool GvtGovt2 { get; set; }
        public bool GvtGovt3 { get; set; }
        public bool GvtGovt4 { get; set; }
        public bool Fac1 { get; set; }
        public bool Fac2 { get; set; }
        public bool Fac3 { get; set; }
        public bool Fac4 { get; set; }
        public string Grouptype { get; set; }
        public string Grouptype1 { get; set; }
        public string Grouptype2 { get; set; }
        public string Grouptype3 { get; set; }
        public string Grouptype4 { get; set; }
        public string Grouptype5 { get; set; }
        public string Grouptype6 { get; set; }
        public string Grouptype7 { get; set; }
        public string Grouptype8 { get; set; }
        public string OtherGroup { get; set; }
        public int? AmtSav { get; set; }
        public string OtherUse { get; set; }
        public string OtherUse1 { get; set; }
        public double? MemNum { get; set; }
        public int? FmCount { get; set; }
        public string Ack2 { get; set; }
        public string Comments { get; set; }
        public string Gps { get; set; }
        public double? GpsLatitude { get; set; }
        public double? GpsLongitude { get; set; }
        public double? GpsAltitude { get; set; }
        public double? GpsPrecision { get; set; }
        public string MetaInstanceId { get; set; }
        public string Uuid { get; set; }
        public string SubmissionTime { get; set; }
        public string Index { get; set; }
        public string ParentTableName { get; set; }
        public string ParentIndex { get; set; }
        public string Tags { get; set; }
        public string Notes { get; set; }
        public string Version { get; set; }
        public string Duration { get; set; }
        public string SubmittedBy { get; set; }
        public string XformId { get; set; }
    }
}
